package com.soltechsystem.model.prl.ViewObject.common;

import java.sql.Date;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Dec 30 11:27:17 PKT 2018
// ---------------------------------------------------------------------
public interface PrlAllowDeductTrxViewRow extends Row {
    Date getDate();
}

