package com.soltechsystem.model.hr.Entity;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.adf.share.ADFContext;

import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed May 15 20:35:40 PKT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ComplaintActionImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        ActionId,
        SeverityId,
        Occurance,
        ActionText,
        CreatedBy,
        UpdatedBy,
        CreationDate,
        UpdationDate,
        VersionNumber;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int ACTIONID = AttributesEnum.ActionId.index();
    public static final int SEVERITYID = AttributesEnum.SeverityId.index();
    public static final int OCCURANCE = AttributesEnum.Occurance.index();
    public static final int ACTIONTEXT = AttributesEnum.ActionText.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int UPDATIONDATE = AttributesEnum.UpdationDate.index();
    public static final int VERSIONNUMBER = AttributesEnum.VersionNumber.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ComplaintActionImpl() {
    }

    /**
     * Gets the attribute value for ActionId, using the alias name ActionId.
     * @return the value of ActionId
     */
    public BigDecimal getActionId() {
        return (BigDecimal) getAttributeInternal(ACTIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ActionId.
     * @param value value to set the ActionId
     */
    public void setActionId(BigDecimal value) {
        setAttributeInternal(ACTIONID, value);
    }

    /**
     * Gets the attribute value for SeverityId, using the alias name SeverityId.
     * @return the value of SeverityId
     */
    public BigDecimal getSeverityId() {
        return (BigDecimal) getAttributeInternal(SEVERITYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SeverityId.
     * @param value value to set the SeverityId
     */
    public void setSeverityId(BigDecimal value) {
        setAttributeInternal(SEVERITYID, value);
    }

    /**
     * Gets the attribute value for Occurance, using the alias name Occurance.
     * @return the value of Occurance
     */
    public BigDecimal getOccurance() {
        return (BigDecimal) getAttributeInternal(OCCURANCE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Occurance.
     * @param value value to set the Occurance
     */
    public void setOccurance(BigDecimal value) {
        setAttributeInternal(OCCURANCE, value);
    }

    /**
     * Gets the attribute value for ActionText, using the alias name ActionText.
     * @return the value of ActionText
     */
    public String getActionText() {
        return (String) getAttributeInternal(ACTIONTEXT);
    }

    /**
     * Sets <code>value</code> as the attribute value for ActionText.
     * @param value value to set the ActionText
     */
    public void setActionText(String value) {
        setAttributeInternal(ACTIONTEXT, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public BigDecimal getCreatedBy() {
        return (BigDecimal) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(BigDecimal value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the value of UpdatedBy
     */
    public BigDecimal getUpdatedBy() {
        return (BigDecimal) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedBy.
     * @param value value to set the UpdatedBy
     */
    public void setUpdatedBy(BigDecimal value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the value of CreationDate
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Timestamp value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for UpdationDate, using the alias name UpdationDate.
     * @return the value of UpdationDate
     */
    public Timestamp getUpdationDate() {
        return (Timestamp) getAttributeInternal(UPDATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdationDate.
     * @param value value to set the UpdationDate
     */
    public void setUpdationDate(Timestamp value) {
        setAttributeInternal(UPDATIONDATE, value);
    }

    /**
     * Gets the attribute value for VersionNumber, using the alias name VersionNumber.
     * @return the value of VersionNumber
     */
    public BigDecimal getVersionNumber() {
        return (BigDecimal) getAttributeInternal(VERSIONNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for VersionNumber.
     * @param value value to set the VersionNumber
     */
    public void setVersionNumber(BigDecimal value) {
        setAttributeInternal(VERSIONNUMBER, value);
    }

    /**
     * @param actionId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal actionId) {
        return new Key(new Object[] { actionId });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.soltechsystem.model.hr.Entity.ComplaintAction");
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        String userid = (ADFContext.getCurrent()
                                   .getSessionScope()
                                   .get("userid") == null) ? "-1" : ADFContext.getCurrent()
                                                                              .getSessionScope()
                                                                              .get("userid")
                                                                              .toString();


        switch (operation) {

        case DML_INSERT:


            setUpdatedBy(new BigDecimal(userid));
            setCreatedBy(new BigDecimal(userid));
            
            break;
        case DML_UPDATE:
            setUpdatedBy(new BigDecimal(userid));

        }
        super.doDML(operation, e);
    }
}

