package com.soltechsystem.model.hr.Entity;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.adf.share.ADFContext;

import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Dec 08 09:09:33 PKT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HrEmployeeKinImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        KinId,
        EmployeeId,
        Relation,
        KinName,
        KinCnic,
        KinContact,
        CreatedBy,
        CreationDate,
        UpdatedBy,
        UpdationDate,
        VersionNumber,
        GuardianName,
        Percentage;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int KINID = AttributesEnum.KinId.index();
    public static final int EMPLOYEEID = AttributesEnum.EmployeeId.index();
    public static final int RELATION = AttributesEnum.Relation.index();
    public static final int KINNAME = AttributesEnum.KinName.index();
    public static final int KINCNIC = AttributesEnum.KinCnic.index();
    public static final int KINCONTACT = AttributesEnum.KinContact.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int UPDATIONDATE = AttributesEnum.UpdationDate.index();
    public static final int VERSIONNUMBER = AttributesEnum.VersionNumber.index();
    public static final int GUARDIANNAME = AttributesEnum.GuardianName.index();
    public static final int PERCENTAGE = AttributesEnum.Percentage.index();

    /**
     * This is the default constructor (do not remove).
     */
    public HrEmployeeKinImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.soltechsystem.model.hr.Entity.HrEmployeeKin");
    }


    /**
     * Gets the attribute value for KinId, using the alias name KinId.
     * @return the value of KinId
     */
    public BigDecimal getKinId() {
        return (BigDecimal) getAttributeInternal(KINID);
    }

    /**
     * Sets <code>value</code> as the attribute value for KinId.
     * @param value value to set the KinId
     */
    public void setKinId(BigDecimal value) {
        setAttributeInternal(KINID, value);
    }

    /**
     * Gets the attribute value for EmployeeId, using the alias name EmployeeId.
     * @return the value of EmployeeId
     */
    public BigDecimal getEmployeeId() {
        return (BigDecimal) getAttributeInternal(EMPLOYEEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for EmployeeId.
     * @param value value to set the EmployeeId
     */
    public void setEmployeeId(BigDecimal value) {
        setAttributeInternal(EMPLOYEEID, value);
    }

    /**
     * Gets the attribute value for Relation, using the alias name Relation.
     * @return the value of Relation
     */
    public BigDecimal getRelation() {
        return (BigDecimal) getAttributeInternal(RELATION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Relation.
     * @param value value to set the Relation
     */
    public void setRelation(BigDecimal value) {
        setAttributeInternal(RELATION, value);
    }

    /**
     * Gets the attribute value for KinName, using the alias name KinName.
     * @return the value of KinName
     */
    public String getKinName() {
        return (String) getAttributeInternal(KINNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for KinName.
     * @param value value to set the KinName
     */
    public void setKinName(String value) {
        setAttributeInternal(KINNAME, value);
    }

    /**
     * Gets the attribute value for KinCnic, using the alias name KinCnic.
     * @return the value of KinCnic
     */
    public String getKinCnic() {
        return (String) getAttributeInternal(KINCNIC);
    }

    /**
     * Sets <code>value</code> as the attribute value for KinCnic.
     * @param value value to set the KinCnic
     */
    public void setKinCnic(String value) {
        setAttributeInternal(KINCNIC, value);
    }

    /**
     * Gets the attribute value for KinContact, using the alias name KinContact.
     * @return the value of KinContact
     */
    public String getKinContact() {
        return (String) getAttributeInternal(KINCONTACT);
    }

    /**
     * Sets <code>value</code> as the attribute value for KinContact.
     * @param value value to set the KinContact
     */
    public void setKinContact(String value) {
        setAttributeInternal(KINCONTACT, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public BigDecimal getCreatedBy() {
        return (BigDecimal) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(BigDecimal value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the value of CreationDate
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the value of UpdatedBy
     */
    public BigDecimal getUpdatedBy() {
        return (BigDecimal) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedBy.
     * @param value value to set the UpdatedBy
     */
    public void setUpdatedBy(BigDecimal value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for UpdationDate, using the alias name UpdationDate.
     * @return the value of UpdationDate
     */
    public Timestamp getUpdationDate() {
        return (Timestamp) getAttributeInternal(UPDATIONDATE);
    }

    /**
     * Gets the attribute value for VersionNumber, using the alias name VersionNumber.
     * @return the value of VersionNumber
     */
    public BigDecimal getVersionNumber() {
        return (BigDecimal) getAttributeInternal(VERSIONNUMBER);
    }


    /**
     * Gets the attribute value for GuardianName, using the alias name GuardianName.
     * @return the value of GuardianName
     */
    public String getGuardianName() {
        return (String) getAttributeInternal(GUARDIANNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for GuardianName.
     * @param value value to set the GuardianName
     */
    public void setGuardianName(String value) {
        setAttributeInternal(GUARDIANNAME, value);
    }

    /**
     * Gets the attribute value for Percentage, using the alias name Percentage.
     * @return the value of Percentage
     */
    public BigDecimal getPercentage() {
        return (BigDecimal) getAttributeInternal(PERCENTAGE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Percentage.
     * @param value value to set the Percentage
     */
    public void setPercentage(BigDecimal value) {
        setAttributeInternal(PERCENTAGE, value);
    }

    /**
     * @param kinId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal kinId) {
        return new Key(new Object[] { kinId });
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        String userid = (ADFContext.getCurrent()
                                   .getSessionScope()
                                   .get("userid") == null) ? "-1" : ADFContext.getCurrent()
                                                                              .getSessionScope()
                                                                              .get("userid")
                                                                              .toString();


        switch (operation) {

        case DML_INSERT:


            setUpdatedBy(new BigDecimal(userid));
            setCreatedBy(new BigDecimal(userid));
          
            break;
        case DML_UPDATE:
            setUpdatedBy(new BigDecimal(userid));

        }
        super.doDML(operation, e);
    }
}

