package com.soltechsystem.model.hr.Entity;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.adf.share.ADFContext;

import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Dec 07 13:58:31 PKT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HrEmployeeAddressImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        AddressId,
        AddressType,
        EmployeeId,
        HouseNumber,
        Street,
        SectorBlock,
        Area,
        Zipcode,
        PoBoxNumber,
        Country,
        StateProvince,
        City,
        Division,
        District,
        Tehsil,
        UnionCouncil,
        PoliceStation,
        Attrib1,
        Attrib2,
        Attrib3,
        Attrib4,
        Attrib5,
        Col1,
        Col2,
        Col3,
        Col4,
        Col5,
        CreatedBy,
        CreationDate,
        UpdatedBy,
        UpdationDate,
        VersionNumber;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ADDRESSID = AttributesEnum.AddressId.index();
    public static final int ADDRESSTYPE = AttributesEnum.AddressType.index();
    public static final int EMPLOYEEID = AttributesEnum.EmployeeId.index();
    public static final int HOUSENUMBER = AttributesEnum.HouseNumber.index();
    public static final int STREET = AttributesEnum.Street.index();
    public static final int SECTORBLOCK = AttributesEnum.SectorBlock.index();
    public static final int AREA = AttributesEnum.Area.index();
    public static final int ZIPCODE = AttributesEnum.Zipcode.index();
    public static final int POBOXNUMBER = AttributesEnum.PoBoxNumber.index();
    public static final int COUNTRY = AttributesEnum.Country.index();
    public static final int STATEPROVINCE = AttributesEnum.StateProvince.index();
    public static final int CITY = AttributesEnum.City.index();
    public static final int DIVISION = AttributesEnum.Division.index();
    public static final int DISTRICT = AttributesEnum.District.index();
    public static final int TEHSIL = AttributesEnum.Tehsil.index();
    public static final int UNIONCOUNCIL = AttributesEnum.UnionCouncil.index();
    public static final int POLICESTATION = AttributesEnum.PoliceStation.index();
    public static final int ATTRIB1 = AttributesEnum.Attrib1.index();
    public static final int ATTRIB2 = AttributesEnum.Attrib2.index();
    public static final int ATTRIB3 = AttributesEnum.Attrib3.index();
    public static final int ATTRIB4 = AttributesEnum.Attrib4.index();
    public static final int ATTRIB5 = AttributesEnum.Attrib5.index();
    public static final int COL1 = AttributesEnum.Col1.index();
    public static final int COL2 = AttributesEnum.Col2.index();
    public static final int COL3 = AttributesEnum.Col3.index();
    public static final int COL4 = AttributesEnum.Col4.index();
    public static final int COL5 = AttributesEnum.Col5.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int UPDATIONDATE = AttributesEnum.UpdationDate.index();
    public static final int VERSIONNUMBER = AttributesEnum.VersionNumber.index();

    /**
     * This is the default constructor (do not remove).
     */
    public HrEmployeeAddressImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.soltechsystem.model.hr.Entity.HrEmployeeAddress");
    }


    /**
     * Gets the attribute value for AddressId, using the alias name AddressId.
     * @return the value of AddressId
     */
    public BigDecimal getAddressId() {
        return (BigDecimal) getAttributeInternal(ADDRESSID);
    }

    /**
     * Sets <code>value</code> as the attribute value for AddressId.
     * @param value value to set the AddressId
     */
    public void setAddressId(BigDecimal value) {
        setAttributeInternal(ADDRESSID, value);
    }

    /**
     * Gets the attribute value for AddressType, using the alias name AddressType.
     * @return the value of AddressType
     */
    public BigDecimal getAddressType() {
        return (BigDecimal) getAttributeInternal(ADDRESSTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for AddressType.
     * @param value value to set the AddressType
     */
    public void setAddressType(BigDecimal value) {
        setAttributeInternal(ADDRESSTYPE, value);
    }

    /**
     * Gets the attribute value for EmployeeId, using the alias name EmployeeId.
     * @return the value of EmployeeId
     */
    public BigDecimal getEmployeeId() {
        return (BigDecimal) getAttributeInternal(EMPLOYEEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for EmployeeId.
     * @param value value to set the EmployeeId
     */
    public void setEmployeeId(BigDecimal value) {
        setAttributeInternal(EMPLOYEEID, value);
    }

    /**
     * Gets the attribute value for HouseNumber, using the alias name HouseNumber.
     * @return the value of HouseNumber
     */
    public String getHouseNumber() {
        return (String) getAttributeInternal(HOUSENUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for HouseNumber.
     * @param value value to set the HouseNumber
     */
    public void setHouseNumber(String value) {
        setAttributeInternal(HOUSENUMBER, value);
    }

    /**
     * Gets the attribute value for Street, using the alias name Street.
     * @return the value of Street
     */
    public String getStreet() {
        return (String) getAttributeInternal(STREET);
    }

    /**
     * Sets <code>value</code> as the attribute value for Street.
     * @param value value to set the Street
     */
    public void setStreet(String value) {
        setAttributeInternal(STREET, value);
    }

    /**
     * Gets the attribute value for SectorBlock, using the alias name SectorBlock.
     * @return the value of SectorBlock
     */
    public String getSectorBlock() {
        return (String) getAttributeInternal(SECTORBLOCK);
    }

    /**
     * Sets <code>value</code> as the attribute value for SectorBlock.
     * @param value value to set the SectorBlock
     */
    public void setSectorBlock(String value) {
        setAttributeInternal(SECTORBLOCK, value);
    }

    /**
     * Gets the attribute value for Area, using the alias name Area.
     * @return the value of Area
     */
    public String getArea() {
        return (String) getAttributeInternal(AREA);
    }

    /**
     * Sets <code>value</code> as the attribute value for Area.
     * @param value value to set the Area
     */
    public void setArea(String value) {
        setAttributeInternal(AREA, value);
    }

    /**
     * Gets the attribute value for Zipcode, using the alias name Zipcode.
     * @return the value of Zipcode
     */
    public String getZipcode() {
        return (String) getAttributeInternal(ZIPCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Zipcode.
     * @param value value to set the Zipcode
     */
    public void setZipcode(String value) {
        setAttributeInternal(ZIPCODE, value);
    }

    /**
     * Gets the attribute value for PoBoxNumber, using the alias name PoBoxNumber.
     * @return the value of PoBoxNumber
     */
    public String getPoBoxNumber() {
        return (String) getAttributeInternal(POBOXNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for PoBoxNumber.
     * @param value value to set the PoBoxNumber
     */
    public void setPoBoxNumber(String value) {
        setAttributeInternal(POBOXNUMBER, value);
    }

    /**
     * Gets the attribute value for Country, using the alias name Country.
     * @return the value of Country
     */
    public BigDecimal getCountry() {
        return (BigDecimal) getAttributeInternal(COUNTRY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Country.
     * @param value value to set the Country
     */
    public void setCountry(BigDecimal value) {
        setAttributeInternal(COUNTRY, value);
    }

    /**
     * Gets the attribute value for StateProvince, using the alias name StateProvince.
     * @return the value of StateProvince
     */
    public BigDecimal getStateProvince() {
        return (BigDecimal) getAttributeInternal(STATEPROVINCE);
    }

    /**
     * Sets <code>value</code> as the attribute value for StateProvince.
     * @param value value to set the StateProvince
     */
    public void setStateProvince(BigDecimal value) {
        setAttributeInternal(STATEPROVINCE, value);
    }

    /**
     * Gets the attribute value for City, using the alias name City.
     * @return the value of City
     */
    public BigDecimal getCity() {
        return (BigDecimal) getAttributeInternal(CITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for City.
     * @param value value to set the City
     */
    public void setCity(BigDecimal value) {
        setAttributeInternal(CITY, value);
    }

    /**
     * Gets the attribute value for Division, using the alias name Division.
     * @return the value of Division
     */
    public BigDecimal getDivision() {
        return (BigDecimal) getAttributeInternal(DIVISION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Division.
     * @param value value to set the Division
     */
    public void setDivision(BigDecimal value) {
        setAttributeInternal(DIVISION, value);
    }

    /**
     * Gets the attribute value for District, using the alias name District.
     * @return the value of District
     */
    public BigDecimal getDistrict() {
        return (BigDecimal) getAttributeInternal(DISTRICT);
    }

    /**
     * Sets <code>value</code> as the attribute value for District.
     * @param value value to set the District
     */
    public void setDistrict(BigDecimal value) {
        setAttributeInternal(DISTRICT, value);
    }

    /**
     * Gets the attribute value for Tehsil, using the alias name Tehsil.
     * @return the value of Tehsil
     */
    public BigDecimal getTehsil() {
        return (BigDecimal) getAttributeInternal(TEHSIL);
    }

    /**
     * Sets <code>value</code> as the attribute value for Tehsil.
     * @param value value to set the Tehsil
     */
    public void setTehsil(BigDecimal value) {
        setAttributeInternal(TEHSIL, value);
    }

    /**
     * Gets the attribute value for UnionCouncil, using the alias name UnionCouncil.
     * @return the value of UnionCouncil
     */
    public String getUnionCouncil() {
        return (String) getAttributeInternal(UNIONCOUNCIL);
    }

    /**
     * Sets <code>value</code> as the attribute value for UnionCouncil.
     * @param value value to set the UnionCouncil
     */
    public void setUnionCouncil(String value) {
        setAttributeInternal(UNIONCOUNCIL, value);
    }

    /**
     * Gets the attribute value for PoliceStation, using the alias name PoliceStation.
     * @return the value of PoliceStation
     */
    public String getPoliceStation() {
        return (String) getAttributeInternal(POLICESTATION);
    }

    /**
     * Sets <code>value</code> as the attribute value for PoliceStation.
     * @param value value to set the PoliceStation
     */
    public void setPoliceStation(String value) {
        setAttributeInternal(POLICESTATION, value);
    }

    /**
     * Gets the attribute value for Attrib1, using the alias name Attrib1.
     * @return the value of Attrib1
     */
    public String getAttrib1() {
        return (String) getAttributeInternal(ATTRIB1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attrib1.
     * @param value value to set the Attrib1
     */
    public void setAttrib1(String value) {
        setAttributeInternal(ATTRIB1, value);
    }

    /**
     * Gets the attribute value for Attrib2, using the alias name Attrib2.
     * @return the value of Attrib2
     */
    public String getAttrib2() {
        return (String) getAttributeInternal(ATTRIB2);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attrib2.
     * @param value value to set the Attrib2
     */
    public void setAttrib2(String value) {
        setAttributeInternal(ATTRIB2, value);
    }

    /**
     * Gets the attribute value for Attrib3, using the alias name Attrib3.
     * @return the value of Attrib3
     */
    public String getAttrib3() {
        return (String) getAttributeInternal(ATTRIB3);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attrib3.
     * @param value value to set the Attrib3
     */
    public void setAttrib3(String value) {
        setAttributeInternal(ATTRIB3, value);
    }

    /**
     * Gets the attribute value for Attrib4, using the alias name Attrib4.
     * @return the value of Attrib4
     */
    public String getAttrib4() {
        return (String) getAttributeInternal(ATTRIB4);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attrib4.
     * @param value value to set the Attrib4
     */
    public void setAttrib4(String value) {
        setAttributeInternal(ATTRIB4, value);
    }

    /**
     * Gets the attribute value for Attrib5, using the alias name Attrib5.
     * @return the value of Attrib5
     */
    public String getAttrib5() {
        return (String) getAttributeInternal(ATTRIB5);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attrib5.
     * @param value value to set the Attrib5
     */
    public void setAttrib5(String value) {
        setAttributeInternal(ATTRIB5, value);
    }

    /**
     * Gets the attribute value for Col1, using the alias name Col1.
     * @return the value of Col1
     */
    public BigDecimal getCol1() {
        return (BigDecimal) getAttributeInternal(COL1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Col1.
     * @param value value to set the Col1
     */
    public void setCol1(BigDecimal value) {
        setAttributeInternal(COL1, value);
    }

    /**
     * Gets the attribute value for Col2, using the alias name Col2.
     * @return the value of Col2
     */
    public BigDecimal getCol2() {
        return (BigDecimal) getAttributeInternal(COL2);
    }

    /**
     * Sets <code>value</code> as the attribute value for Col2.
     * @param value value to set the Col2
     */
    public void setCol2(BigDecimal value) {
        setAttributeInternal(COL2, value);
    }

    /**
     * Gets the attribute value for Col3, using the alias name Col3.
     * @return the value of Col3
     */
    public BigDecimal getCol3() {
        return (BigDecimal) getAttributeInternal(COL3);
    }

    /**
     * Sets <code>value</code> as the attribute value for Col3.
     * @param value value to set the Col3
     */
    public void setCol3(BigDecimal value) {
        setAttributeInternal(COL3, value);
    }

    /**
     * Gets the attribute value for Col4, using the alias name Col4.
     * @return the value of Col4
     */
    public BigDecimal getCol4() {
        return (BigDecimal) getAttributeInternal(COL4);
    }

    /**
     * Sets <code>value</code> as the attribute value for Col4.
     * @param value value to set the Col4
     */
    public void setCol4(BigDecimal value) {
        setAttributeInternal(COL4, value);
    }

    /**
     * Gets the attribute value for Col5, using the alias name Col5.
     * @return the value of Col5
     */
    public BigDecimal getCol5() {
        return (BigDecimal) getAttributeInternal(COL5);
    }

    /**
     * Sets <code>value</code> as the attribute value for Col5.
     * @param value value to set the Col5
     */
    public void setCol5(BigDecimal value) {
        setAttributeInternal(COL5, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public BigDecimal getCreatedBy() {
        return (BigDecimal) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(BigDecimal value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the value of CreationDate
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the value of UpdatedBy
     */
    public BigDecimal getUpdatedBy() {
        return (BigDecimal) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedBy.
     * @param value value to set the UpdatedBy
     */
    public void setUpdatedBy(BigDecimal value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for UpdationDate, using the alias name UpdationDate.
     * @return the value of UpdationDate
     */
    public Timestamp getUpdationDate() {
        return (Timestamp) getAttributeInternal(UPDATIONDATE);
    }

    /**
     * Gets the attribute value for VersionNumber, using the alias name VersionNumber.
     * @return the value of VersionNumber
     */
    public BigDecimal getVersionNumber() {
        return (BigDecimal) getAttributeInternal(VERSIONNUMBER);
    }


    /**
     * @param addressId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal addressId) {
        return new Key(new Object[] { addressId });
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        String userid = (ADFContext.getCurrent()
                                   .getSessionScope()
                                   .get("userid") == null) ? "-1" : ADFContext.getCurrent()
                                                                              .getSessionScope()
                                                                              .get("userid")
                                                                              .toString();


        switch (operation) {

        case DML_INSERT:


            setUpdatedBy(new BigDecimal(userid));
            setCreatedBy(new BigDecimal(userid));

            break;
        case DML_UPDATE:
            setUpdatedBy(new BigDecimal(userid));

        }
        super.doDML(operation, e);
    }
}

