package com.soltechsystem.model.hr.Entity;

import com.soltechsystem.model.sys.Entity.SysUsersImpl;

import java.math.BigDecimal;

import java.sql.CallableStatement;
import java.sql.Timestamp;

import oracle.adf.share.ADFContext;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Dec 04 10:37:18 PKT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HrEmployeesImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        EmployeeId,
        FirstName,
        MiddleName,
        LastName,
        UserCreated,
        LocationId,
        JobId,
        JoiningDate,
        GradeId,
        EmployeeTypeId,
        EmployeeCode,
        EmployeeStatus,
        ProbationStartDate,
        ProbationEndDate,
        ConfirmationDate,
        EffectiveStartDate,
        EffectiveEndDate,
        CostToCompany,
        ManagerId,
        DepartmentId,
        EmployeeNtn,
        Salutation,
        FatherOrHusbandName,
        DateOfBirth,
        Gender,
        MartialStatus,
        Nationality,
        EmployeeCnic,
        CnicExpiryDate,
        PassportNumber,
        PassportExpiryDate,
        DrivingLicenseNumber,
        LicenseExpiryDate,
        BloodGroup,
        IdentityMark,
        Col1,
        Col2,
        Col3,
        Col4,
        Col5,
        Col6,
        Col7,
        Col8,
        Col9,
        Col10,
        Col11,
        Col12,
        Col13,
        Col14,
        Attrib1,
        Attrib2,
        Attrib3,
        Attrib4,
        Attrib5,
        Attrib6,
        Attrib7,
        Attrib8,
        Attrib9,
        Attrib10,
        Attrib11,
        Attrib12,
        Attrib13,
        Attrib14,
        Attrib15,
        CreatedBy,
        CreationDate,
        UpdatedBy,
        UpdationDate,
        VersionNumber,
        EmailAddress,
        DrivingLicExpiry,
        GrossPay,
        PaymentMode,
        BankId,
        AccountNumber,
        EmployeeActive,
        FamilyNumber,
        NoticePeriodStartDate,
        ResignationDate,
        BasicPay,
        HrJobs,
        ManagerIdHrEmployees,
        HrEmployees,
        HrDepartments,
        SysUsers;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int EMPLOYEEID = AttributesEnum.EmployeeId.index();
    public static final int FIRSTNAME = AttributesEnum.FirstName.index();
    public static final int MIDDLENAME = AttributesEnum.MiddleName.index();
    public static final int LASTNAME = AttributesEnum.LastName.index();
    public static final int USERCREATED = AttributesEnum.UserCreated.index();
    public static final int LOCATIONID = AttributesEnum.LocationId.index();
    public static final int JOBID = AttributesEnum.JobId.index();
    public static final int JOININGDATE = AttributesEnum.JoiningDate.index();
    public static final int GRADEID = AttributesEnum.GradeId.index();
    public static final int EMPLOYEETYPEID = AttributesEnum.EmployeeTypeId.index();
    public static final int EMPLOYEECODE = AttributesEnum.EmployeeCode.index();
    public static final int EMPLOYEESTATUS = AttributesEnum.EmployeeStatus.index();
    public static final int PROBATIONSTARTDATE = AttributesEnum.ProbationStartDate.index();
    public static final int PROBATIONENDDATE = AttributesEnum.ProbationEndDate.index();
    public static final int CONFIRMATIONDATE = AttributesEnum.ConfirmationDate.index();
    public static final int EFFECTIVESTARTDATE = AttributesEnum.EffectiveStartDate.index();
    public static final int EFFECTIVEENDDATE = AttributesEnum.EffectiveEndDate.index();
    public static final int COSTTOCOMPANY = AttributesEnum.CostToCompany.index();
    public static final int MANAGERID = AttributesEnum.ManagerId.index();
    public static final int DEPARTMENTID = AttributesEnum.DepartmentId.index();
    public static final int EMPLOYEENTN = AttributesEnum.EmployeeNtn.index();
    public static final int SALUTATION = AttributesEnum.Salutation.index();
    public static final int FATHERORHUSBANDNAME = AttributesEnum.FatherOrHusbandName.index();
    public static final int DATEOFBIRTH = AttributesEnum.DateOfBirth.index();
    public static final int GENDER = AttributesEnum.Gender.index();
    public static final int MARTIALSTATUS = AttributesEnum.MartialStatus.index();
    public static final int NATIONALITY = AttributesEnum.Nationality.index();
    public static final int EMPLOYEECNIC = AttributesEnum.EmployeeCnic.index();
    public static final int CNICEXPIRYDATE = AttributesEnum.CnicExpiryDate.index();
    public static final int PASSPORTNUMBER = AttributesEnum.PassportNumber.index();
    public static final int PASSPORTEXPIRYDATE = AttributesEnum.PassportExpiryDate.index();
    public static final int DRIVINGLICENSENUMBER = AttributesEnum.DrivingLicenseNumber.index();
    public static final int LICENSEEXPIRYDATE = AttributesEnum.LicenseExpiryDate.index();
    public static final int BLOODGROUP = AttributesEnum.BloodGroup.index();
    public static final int IDENTITYMARK = AttributesEnum.IdentityMark.index();
    public static final int COL1 = AttributesEnum.Col1.index();
    public static final int COL2 = AttributesEnum.Col2.index();
    public static final int COL3 = AttributesEnum.Col3.index();
    public static final int COL4 = AttributesEnum.Col4.index();
    public static final int COL5 = AttributesEnum.Col5.index();
    public static final int COL6 = AttributesEnum.Col6.index();
    public static final int COL7 = AttributesEnum.Col7.index();
    public static final int COL8 = AttributesEnum.Col8.index();
    public static final int COL9 = AttributesEnum.Col9.index();
    public static final int COL10 = AttributesEnum.Col10.index();
    public static final int COL11 = AttributesEnum.Col11.index();
    public static final int COL12 = AttributesEnum.Col12.index();
    public static final int COL13 = AttributesEnum.Col13.index();
    public static final int COL14 = AttributesEnum.Col14.index();
    public static final int ATTRIB1 = AttributesEnum.Attrib1.index();
    public static final int ATTRIB2 = AttributesEnum.Attrib2.index();
    public static final int ATTRIB3 = AttributesEnum.Attrib3.index();
    public static final int ATTRIB4 = AttributesEnum.Attrib4.index();
    public static final int ATTRIB5 = AttributesEnum.Attrib5.index();
    public static final int ATTRIB6 = AttributesEnum.Attrib6.index();
    public static final int ATTRIB7 = AttributesEnum.Attrib7.index();
    public static final int ATTRIB8 = AttributesEnum.Attrib8.index();
    public static final int ATTRIB9 = AttributesEnum.Attrib9.index();
    public static final int ATTRIB10 = AttributesEnum.Attrib10.index();
    public static final int ATTRIB11 = AttributesEnum.Attrib11.index();
    public static final int ATTRIB12 = AttributesEnum.Attrib12.index();
    public static final int ATTRIB13 = AttributesEnum.Attrib13.index();
    public static final int ATTRIB14 = AttributesEnum.Attrib14.index();
    public static final int ATTRIB15 = AttributesEnum.Attrib15.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int UPDATIONDATE = AttributesEnum.UpdationDate.index();
    public static final int VERSIONNUMBER = AttributesEnum.VersionNumber.index();
    public static final int EMAILADDRESS = AttributesEnum.EmailAddress.index();
    public static final int DRIVINGLICEXPIRY = AttributesEnum.DrivingLicExpiry.index();
    public static final int GROSSPAY = AttributesEnum.GrossPay.index();
    public static final int PAYMENTMODE = AttributesEnum.PaymentMode.index();
    public static final int BANKID = AttributesEnum.BankId.index();
    public static final int ACCOUNTNUMBER = AttributesEnum.AccountNumber.index();
    public static final int EMPLOYEEACTIVE = AttributesEnum.EmployeeActive.index();
    public static final int FAMILYNUMBER = AttributesEnum.FamilyNumber.index();
    public static final int NOTICEPERIODSTARTDATE = AttributesEnum.NoticePeriodStartDate.index();
    public static final int RESIGNATIONDATE = AttributesEnum.ResignationDate.index();
    public static final int BASICPAY = AttributesEnum.BasicPay.index();
    public static final int HRJOBS = AttributesEnum.HrJobs.index();
    public static final int MANAGERIDHREMPLOYEES = AttributesEnum.ManagerIdHrEmployees.index();
    public static final int HREMPLOYEES = AttributesEnum.HrEmployees.index();
    public static final int HRDEPARTMENTS = AttributesEnum.HrDepartments.index();
    public static final int SYSUSERS = AttributesEnum.SysUsers.index();

    /**
     * This is the default constructor (do not remove).
     */
    public HrEmployeesImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.soltechsystem.model.hr.Entity.HrEmployees");
    }


    /**
     * Gets the attribute value for EmployeeId, using the alias name EmployeeId.
     * @return the value of EmployeeId
     */
    public BigDecimal getEmployeeId() {
        return (BigDecimal) getAttributeInternal(EMPLOYEEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for EmployeeId.
     * @param value value to set the EmployeeId
     */
    public void setEmployeeId(BigDecimal value) {
        setAttributeInternal(EMPLOYEEID, value);
    }

    /**
     * Gets the attribute value for FirstName, using the alias name FirstName.
     * @return the value of FirstName
     */
    public String getFirstName() {
        return (String) getAttributeInternal(FIRSTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for FirstName.
     * @param value value to set the FirstName
     */
    public void setFirstName(String value) {
        setAttributeInternal(FIRSTNAME, value);
    }

    /**
     * Gets the attribute value for MiddleName, using the alias name MiddleName.
     * @return the value of MiddleName
     */
    public String getMiddleName() {
        return (String) getAttributeInternal(MIDDLENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for MiddleName.
     * @param value value to set the MiddleName
     */
    public void setMiddleName(String value) {
        setAttributeInternal(MIDDLENAME, value);
    }

    /**
     * Gets the attribute value for LastName, using the alias name LastName.
     * @return the value of LastName
     */
    public String getLastName() {
        return (String) getAttributeInternal(LASTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastName.
     * @param value value to set the LastName
     */
    public void setLastName(String value) {
        setAttributeInternal(LASTNAME, value);
    }

    /**
     * Gets the attribute value for UserCreated, using the alias name UserCreated.
     * @return the value of UserCreated
     */
    public String getUserCreated() {
        return (String) getAttributeInternal(USERCREATED);
    }

    /**
     * Sets <code>value</code> as the attribute value for UserCreated.
     * @param value value to set the UserCreated
     */
    public void setUserCreated(String value) {
        setAttributeInternal(USERCREATED, value);
    }

    /**
     * Gets the attribute value for LocationId, using the alias name LocationId.
     * @return the value of LocationId
     */
    public BigDecimal getLocationId() {
        return (BigDecimal) getAttributeInternal(LOCATIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for LocationId.
     * @param value value to set the LocationId
     */
    public void setLocationId(BigDecimal value) {
        setAttributeInternal(LOCATIONID, value);
    }

    /**
     * Gets the attribute value for JobId, using the alias name JobId.
     * @return the value of JobId
     */
    public BigDecimal getJobId() {
        return (BigDecimal) getAttributeInternal(JOBID);
    }

    /**
     * Sets <code>value</code> as the attribute value for JobId.
     * @param value value to set the JobId
     */
    public void setJobId(BigDecimal value) {
        setAttributeInternal(JOBID, value);
    }

    /**
     * Gets the attribute value for JoiningDate, using the alias name JoiningDate.
     * @return the value of JoiningDate
     */
    public Timestamp getJoiningDate() {
        return (Timestamp) getAttributeInternal(JOININGDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for JoiningDate.
     * @param value value to set the JoiningDate
     */
    public void setJoiningDate(Timestamp value) {
        setAttributeInternal(JOININGDATE, value);
    }

    /**
     * Gets the attribute value for GradeId, using the alias name GradeId.
     * @return the value of GradeId
     */
    public BigDecimal getGradeId() {
        return (BigDecimal) getAttributeInternal(GRADEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for GradeId.
     * @param value value to set the GradeId
     */
    public void setGradeId(BigDecimal value) {
        setAttributeInternal(GRADEID, value);
    }

    /**
     * Gets the attribute value for EmployeeTypeId, using the alias name EmployeeTypeId.
     * @return the value of EmployeeTypeId
     */
    public BigDecimal getEmployeeTypeId() {
        return (BigDecimal) getAttributeInternal(EMPLOYEETYPEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for EmployeeTypeId.
     * @param value value to set the EmployeeTypeId
     */
    public void setEmployeeTypeId(BigDecimal value) {
        setAttributeInternal(EMPLOYEETYPEID, value);
    }

    /**
     * Gets the attribute value for EmployeeCode, using the alias name EmployeeCode.
     * @return the value of EmployeeCode
     */
    public String getEmployeeCode() {
        return (String) getAttributeInternal(EMPLOYEECODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for EmployeeCode.
     * @param value value to set the EmployeeCode
     */
    public void setEmployeeCode(String value) {
        setAttributeInternal(EMPLOYEECODE, value);
    }

    /**
     * Gets the attribute value for EmployeeStatus, using the alias name EmployeeStatus.
     * @return the value of EmployeeStatus
     */
    public BigDecimal getEmployeeStatus() {
        return (BigDecimal) getAttributeInternal(EMPLOYEESTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for EmployeeStatus.
     * @param value value to set the EmployeeStatus
     */
    public void setEmployeeStatus(BigDecimal value) {
        setAttributeInternal(EMPLOYEESTATUS, value);
    }

    /**
     * Gets the attribute value for ProbationStartDate, using the alias name ProbationStartDate.
     * @return the value of ProbationStartDate
     */
    public Timestamp getProbationStartDate() {
        return (Timestamp) getAttributeInternal(PROBATIONSTARTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProbationStartDate.
     * @param value value to set the ProbationStartDate
     */
    public void setProbationStartDate(Timestamp value) {
        setAttributeInternal(PROBATIONSTARTDATE, value);
    }

    /**
     * Gets the attribute value for ProbationEndDate, using the alias name ProbationEndDate.
     * @return the value of ProbationEndDate
     */
    public Timestamp getProbationEndDate() {
        return (Timestamp) getAttributeInternal(PROBATIONENDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProbationEndDate.
     * @param value value to set the ProbationEndDate
     */
    public void setProbationEndDate(Timestamp value) {
        setAttributeInternal(PROBATIONENDDATE, value);
    }

    /**
     * Gets the attribute value for ConfirmationDate, using the alias name ConfirmationDate.
     * @return the value of ConfirmationDate
     */
    public Timestamp getConfirmationDate() {
        return (Timestamp) getAttributeInternal(CONFIRMATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ConfirmationDate.
     * @param value value to set the ConfirmationDate
     */
    public void setConfirmationDate(Timestamp value) {
        setAttributeInternal(CONFIRMATIONDATE, value);
    }

    /**
     * Gets the attribute value for EffectiveStartDate, using the alias name EffectiveStartDate.
     * @return the value of EffectiveStartDate
     */
    public Timestamp getEffectiveStartDate() {
        return (Timestamp) getAttributeInternal(EFFECTIVESTARTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for EffectiveStartDate.
     * @param value value to set the EffectiveStartDate
     */
    public void setEffectiveStartDate(Timestamp value) {
        setAttributeInternal(EFFECTIVESTARTDATE, value);
    }

    /**
     * Gets the attribute value for EffectiveEndDate, using the alias name EffectiveEndDate.
     * @return the value of EffectiveEndDate
     */
    public Timestamp getEffectiveEndDate() {
        return (Timestamp) getAttributeInternal(EFFECTIVEENDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for EffectiveEndDate.
     * @param value value to set the EffectiveEndDate
     */
    public void setEffectiveEndDate(Timestamp value) {
        setAttributeInternal(EFFECTIVEENDDATE, value);
    }

    /**
     * Gets the attribute value for CostToCompany, using the alias name CostToCompany.
     * @return the value of CostToCompany
     */
    public BigDecimal getCostToCompany() {
        return (BigDecimal) getAttributeInternal(COSTTOCOMPANY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CostToCompany.
     * @param value value to set the CostToCompany
     */
    public void setCostToCompany(BigDecimal value) {
        setAttributeInternal(COSTTOCOMPANY, value);
    }

    /**
     * Gets the attribute value for ManagerId, using the alias name ManagerId.
     * @return the value of ManagerId
     */
    public BigDecimal getManagerId() {
        return (BigDecimal) getAttributeInternal(MANAGERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ManagerId.
     * @param value value to set the ManagerId
     */
    public void setManagerId(BigDecimal value) {
        setAttributeInternal(MANAGERID, value);
    }

    /**
     * Gets the attribute value for DepartmentId, using the alias name DepartmentId.
     * @return the value of DepartmentId
     */
    public BigDecimal getDepartmentId() {
        return (BigDecimal) getAttributeInternal(DEPARTMENTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DepartmentId.
     * @param value value to set the DepartmentId
     */
    public void setDepartmentId(BigDecimal value) {
        setAttributeInternal(DEPARTMENTID, value);
    }

    /**
     * Gets the attribute value for EmployeeNtn, using the alias name EmployeeNtn.
     * @return the value of EmployeeNtn
     */
    public String getEmployeeNtn() {
        return (String) getAttributeInternal(EMPLOYEENTN);
    }

    /**
     * Sets <code>value</code> as the attribute value for EmployeeNtn.
     * @param value value to set the EmployeeNtn
     */
    public void setEmployeeNtn(String value) {
        setAttributeInternal(EMPLOYEENTN, value);
    }

    /**
     * Gets the attribute value for Salutation, using the alias name Salutation.
     * @return the value of Salutation
     */
    public String getSalutation() {
        return (String) getAttributeInternal(SALUTATION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Salutation.
     * @param value value to set the Salutation
     */
    public void setSalutation(String value) {
        setAttributeInternal(SALUTATION, value);
    }

    /**
     * Gets the attribute value for FatherOrHusbandName, using the alias name FatherOrHusbandName.
     * @return the value of FatherOrHusbandName
     */
    public String getFatherOrHusbandName() {
        return (String) getAttributeInternal(FATHERORHUSBANDNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for FatherOrHusbandName.
     * @param value value to set the FatherOrHusbandName
     */
    public void setFatherOrHusbandName(String value) {
        setAttributeInternal(FATHERORHUSBANDNAME, value);
    }

    /**
     * Gets the attribute value for DateOfBirth, using the alias name DateOfBirth.
     * @return the value of DateOfBirth
     */
    public Timestamp getDateOfBirth() {
        return (Timestamp) getAttributeInternal(DATEOFBIRTH);
    }

    /**
     * Sets <code>value</code> as the attribute value for DateOfBirth.
     * @param value value to set the DateOfBirth
     */
    public void setDateOfBirth(Timestamp value) {
        setAttributeInternal(DATEOFBIRTH, value);
    }

    /**
     * Gets the attribute value for Gender, using the alias name Gender.
     * @return the value of Gender
     */
    public String getGender() {
        return (String) getAttributeInternal(GENDER);
    }

    /**
     * Sets <code>value</code> as the attribute value for Gender.
     * @param value value to set the Gender
     */
    public void setGender(String value) {
        setAttributeInternal(GENDER, value);
    }

    /**
     * Gets the attribute value for MartialStatus, using the alias name MartialStatus.
     * @return the value of MartialStatus
     */
    public String getMartialStatus() {
        return (String) getAttributeInternal(MARTIALSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for MartialStatus.
     * @param value value to set the MartialStatus
     */
    public void setMartialStatus(String value) {
        setAttributeInternal(MARTIALSTATUS, value);
    }

    /**
     * Gets the attribute value for Nationality, using the alias name Nationality.
     * @return the value of Nationality
     */
    public String getNationality() {
        return (String) getAttributeInternal(NATIONALITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Nationality.
     * @param value value to set the Nationality
     */
    public void setNationality(String value) {
        setAttributeInternal(NATIONALITY, value);
    }

    /**
     * Gets the attribute value for EmployeeCnic, using the alias name EmployeeCnic.
     * @return the value of EmployeeCnic
     */
    public String getEmployeeCnic() {
        return (String) getAttributeInternal(EMPLOYEECNIC);
    }

    /**
     * Sets <code>value</code> as the attribute value for EmployeeCnic.
     * @param value value to set the EmployeeCnic
     */
    public void setEmployeeCnic(String value) {
        setAttributeInternal(EMPLOYEECNIC, value);
    }

    /**
     * Gets the attribute value for CnicExpiryDate, using the alias name CnicExpiryDate.
     * @return the value of CnicExpiryDate
     */
    public Timestamp getCnicExpiryDate() {
        return (Timestamp) getAttributeInternal(CNICEXPIRYDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CnicExpiryDate.
     * @param value value to set the CnicExpiryDate
     */
    public void setCnicExpiryDate(Timestamp value) {
        setAttributeInternal(CNICEXPIRYDATE, value);
    }

    /**
     * Gets the attribute value for PassportNumber, using the alias name PassportNumber.
     * @return the value of PassportNumber
     */
    public String getPassportNumber() {
        return (String) getAttributeInternal(PASSPORTNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for PassportNumber.
     * @param value value to set the PassportNumber
     */
    public void setPassportNumber(String value) {
        setAttributeInternal(PASSPORTNUMBER, value);
    }

    /**
     * Gets the attribute value for PassportExpiryDate, using the alias name PassportExpiryDate.
     * @return the value of PassportExpiryDate
     */
    public Timestamp getPassportExpiryDate() {
        return (Timestamp) getAttributeInternal(PASSPORTEXPIRYDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for PassportExpiryDate.
     * @param value value to set the PassportExpiryDate
     */
    public void setPassportExpiryDate(Timestamp value) {
        setAttributeInternal(PASSPORTEXPIRYDATE, value);
    }

    /**
     * Gets the attribute value for DrivingLicenseNumber, using the alias name DrivingLicenseNumber.
     * @return the value of DrivingLicenseNumber
     */
    public String getDrivingLicenseNumber() {
        return (String) getAttributeInternal(DRIVINGLICENSENUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for DrivingLicenseNumber.
     * @param value value to set the DrivingLicenseNumber
     */
    public void setDrivingLicenseNumber(String value) {
        setAttributeInternal(DRIVINGLICENSENUMBER, value);
    }

    /**
     * Gets the attribute value for LicenseExpiryDate, using the alias name LicenseExpiryDate.
     * @return the value of LicenseExpiryDate
     */
    public Timestamp getLicenseExpiryDate() {
        return (Timestamp) getAttributeInternal(LICENSEEXPIRYDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LicenseExpiryDate.
     * @param value value to set the LicenseExpiryDate
     */
    public void setLicenseExpiryDate(Timestamp value) {
        setAttributeInternal(LICENSEEXPIRYDATE, value);
    }

    /**
     * Gets the attribute value for BloodGroup, using the alias name BloodGroup.
     * @return the value of BloodGroup
     */
    public BigDecimal getBloodGroup() {
        return (BigDecimal) getAttributeInternal(BLOODGROUP);
    }

    /**
     * Sets <code>value</code> as the attribute value for BloodGroup.
     * @param value value to set the BloodGroup
     */
    public void setBloodGroup(BigDecimal value) {
        setAttributeInternal(BLOODGROUP, value);
    }

    /**
     * Gets the attribute value for IdentityMark, using the alias name IdentityMark.
     * @return the value of IdentityMark
     */
    public String getIdentityMark() {
        return (String) getAttributeInternal(IDENTITYMARK);
    }

    /**
     * Sets <code>value</code> as the attribute value for IdentityMark.
     * @param value value to set the IdentityMark
     */
    public void setIdentityMark(String value) {
        setAttributeInternal(IDENTITYMARK, value);
    }

    /**
     * Gets the attribute value for Col1, using the alias name Col1.
     * @return the value of Col1
     */
    public BigDecimal getCol1() {
        return (BigDecimal) getAttributeInternal(COL1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Col1.
     * @param value value to set the Col1
     */
    public void setCol1(BigDecimal value) {
        setAttributeInternal(COL1, value);
    }

    /**
     * Gets the attribute value for Col2, using the alias name Col2.
     * @return the value of Col2
     */
    public BigDecimal getCol2() {
        return (BigDecimal) getAttributeInternal(COL2);
    }

    /**
     * Sets <code>value</code> as the attribute value for Col2.
     * @param value value to set the Col2
     */
    public void setCol2(BigDecimal value) {
        setAttributeInternal(COL2, value);
    }

    /**
     * Gets the attribute value for Col3, using the alias name Col3.
     * @return the value of Col3
     */
    public BigDecimal getCol3() {
        return (BigDecimal) getAttributeInternal(COL3);
    }

    /**
     * Sets <code>value</code> as the attribute value for Col3.
     * @param value value to set the Col3
     */
    public void setCol3(BigDecimal value) {
        setAttributeInternal(COL3, value);
    }

    /**
     * Gets the attribute value for Col4, using the alias name Col4.
     * @return the value of Col4
     */
    public BigDecimal getCol4() {
        return (BigDecimal) getAttributeInternal(COL4);
    }

    /**
     * Sets <code>value</code> as the attribute value for Col4.
     * @param value value to set the Col4
     */
    public void setCol4(BigDecimal value) {
        setAttributeInternal(COL4, value);
    }

    /**
     * Gets the attribute value for Col5, using the alias name Col5.
     * @return the value of Col5
     */
    public BigDecimal getCol5() {
        return (BigDecimal) getAttributeInternal(COL5);
    }

    /**
     * Sets <code>value</code> as the attribute value for Col5.
     * @param value value to set the Col5
     */
    public void setCol5(BigDecimal value) {
        setAttributeInternal(COL5, value);
    }

    /**
     * Gets the attribute value for Col6, using the alias name Col6.
     * @return the value of Col6
     */
    public BigDecimal getCol6() {
        return (BigDecimal) getAttributeInternal(COL6);
    }

    /**
     * Sets <code>value</code> as the attribute value for Col6.
     * @param value value to set the Col6
     */
    public void setCol6(BigDecimal value) {
        setAttributeInternal(COL6, value);
    }

    /**
     * Gets the attribute value for Col7, using the alias name Col7.
     * @return the value of Col7
     */
    public BigDecimal getCol7() {
        return (BigDecimal) getAttributeInternal(COL7);
    }

    /**
     * Sets <code>value</code> as the attribute value for Col7.
     * @param value value to set the Col7
     */
    public void setCol7(BigDecimal value) {
        setAttributeInternal(COL7, value);
    }

    /**
     * Gets the attribute value for Col8, using the alias name Col8.
     * @return the value of Col8
     */
    public BigDecimal getCol8() {
        return (BigDecimal) getAttributeInternal(COL8);
    }

    /**
     * Sets <code>value</code> as the attribute value for Col8.
     * @param value value to set the Col8
     */
    public void setCol8(BigDecimal value) {
        setAttributeInternal(COL8, value);
    }

    /**
     * Gets the attribute value for Col9, using the alias name Col9.
     * @return the value of Col9
     */
    public BigDecimal getCol9() {
        return (BigDecimal) getAttributeInternal(COL9);
    }

    /**
     * Sets <code>value</code> as the attribute value for Col9.
     * @param value value to set the Col9
     */
    public void setCol9(BigDecimal value) {
        setAttributeInternal(COL9, value);
    }

    /**
     * Gets the attribute value for Col10, using the alias name Col10.
     * @return the value of Col10
     */
    public BigDecimal getCol10() {
        return (BigDecimal) getAttributeInternal(COL10);
    }

    /**
     * Sets <code>value</code> as the attribute value for Col10.
     * @param value value to set the Col10
     */
    public void setCol10(BigDecimal value) {
        setAttributeInternal(COL10, value);
    }

    /**
     * Gets the attribute value for Col11, using the alias name Col11.
     * @return the value of Col11
     */
    public BigDecimal getCol11() {
        return (BigDecimal) getAttributeInternal(COL11);
    }

    /**
     * Sets <code>value</code> as the attribute value for Col11.
     * @param value value to set the Col11
     */
    public void setCol11(BigDecimal value) {
        setAttributeInternal(COL11, value);
    }

    /**
     * Gets the attribute value for Col12, using the alias name Col12.
     * @return the value of Col12
     */
    public BigDecimal getCol12() {
        return (BigDecimal) getAttributeInternal(COL12);
    }

    /**
     * Sets <code>value</code> as the attribute value for Col12.
     * @param value value to set the Col12
     */
    public void setCol12(BigDecimal value) {
        setAttributeInternal(COL12, value);
    }

    /**
     * Gets the attribute value for Col13, using the alias name Col13.
     * @return the value of Col13
     */
    public BigDecimal getCol13() {
        return (BigDecimal) getAttributeInternal(COL13);
    }

    /**
     * Sets <code>value</code> as the attribute value for Col13.
     * @param value value to set the Col13
     */
    public void setCol13(BigDecimal value) {
        setAttributeInternal(COL13, value);
    }

    /**
     * Gets the attribute value for Col14, using the alias name Col14.
     * @return the value of Col14
     */
    public BigDecimal getCol14() {
        return (BigDecimal) getAttributeInternal(COL14);
    }

    /**
     * Sets <code>value</code> as the attribute value for Col14.
     * @param value value to set the Col14
     */
    public void setCol14(BigDecimal value) {
        setAttributeInternal(COL14, value);
    }

    /**
     * Gets the attribute value for Attrib1, using the alias name Attrib1.
     * @return the value of Attrib1
     */
    public String getAttrib1() {
        return (String) getAttributeInternal(ATTRIB1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attrib1.
     * @param value value to set the Attrib1
     */
    public void setAttrib1(String value) {
        setAttributeInternal(ATTRIB1, value);
    }

    /**
     * Gets the attribute value for Attrib2, using the alias name Attrib2.
     * @return the value of Attrib2
     */
    public String getAttrib2() {
        return (String) getAttributeInternal(ATTRIB2);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attrib2.
     * @param value value to set the Attrib2
     */
    public void setAttrib2(String value) {
        setAttributeInternal(ATTRIB2, value);
    }

    /**
     * Gets the attribute value for Attrib3, using the alias name Attrib3.
     * @return the value of Attrib3
     */
    public String getAttrib3() {
        return (String) getAttributeInternal(ATTRIB3);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attrib3.
     * @param value value to set the Attrib3
     */
    public void setAttrib3(String value) {
        setAttributeInternal(ATTRIB3, value);
    }

    /**
     * Gets the attribute value for Attrib4, using the alias name Attrib4.
     * @return the value of Attrib4
     */
    public String getAttrib4() {
        return (String) getAttributeInternal(ATTRIB4);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attrib4.
     * @param value value to set the Attrib4
     */
    public void setAttrib4(String value) {
        setAttributeInternal(ATTRIB4, value);
    }

    /**
     * Gets the attribute value for Attrib5, using the alias name Attrib5.
     * @return the value of Attrib5
     */
    public String getAttrib5() {
        return (String) getAttributeInternal(ATTRIB5);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attrib5.
     * @param value value to set the Attrib5
     */
    public void setAttrib5(String value) {
        setAttributeInternal(ATTRIB5, value);
    }

    /**
     * Gets the attribute value for Attrib6, using the alias name Attrib6.
     * @return the value of Attrib6
     */
    public String getAttrib6() {
        return (String) getAttributeInternal(ATTRIB6);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attrib6.
     * @param value value to set the Attrib6
     */
    public void setAttrib6(String value) {
        setAttributeInternal(ATTRIB6, value);
    }

    /**
     * Gets the attribute value for Attrib7, using the alias name Attrib7.
     * @return the value of Attrib7
     */
    public String getAttrib7() {
        return (String) getAttributeInternal(ATTRIB7);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attrib7.
     * @param value value to set the Attrib7
     */
    public void setAttrib7(String value) {
        setAttributeInternal(ATTRIB7, value);
    }

    /**
     * Gets the attribute value for Attrib8, using the alias name Attrib8.
     * @return the value of Attrib8
     */
    public String getAttrib8() {
        return (String) getAttributeInternal(ATTRIB8);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attrib8.
     * @param value value to set the Attrib8
     */
    public void setAttrib8(String value) {
        setAttributeInternal(ATTRIB8, value);
    }

    /**
     * Gets the attribute value for Attrib9, using the alias name Attrib9.
     * @return the value of Attrib9
     */
    public String getAttrib9() {
        return (String) getAttributeInternal(ATTRIB9);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attrib9.
     * @param value value to set the Attrib9
     */
    public void setAttrib9(String value) {
        setAttributeInternal(ATTRIB9, value);
    }

    /**
     * Gets the attribute value for Attrib10, using the alias name Attrib10.
     * @return the value of Attrib10
     */
    public String getAttrib10() {
        return (String) getAttributeInternal(ATTRIB10);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attrib10.
     * @param value value to set the Attrib10
     */
    public void setAttrib10(String value) {
        setAttributeInternal(ATTRIB10, value);
    }

    /**
     * Gets the attribute value for Attrib11, using the alias name Attrib11.
     * @return the value of Attrib11
     */
    public String getAttrib11() {
        return (String) getAttributeInternal(ATTRIB11);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attrib11.
     * @param value value to set the Attrib11
     */
    public void setAttrib11(String value) {
        setAttributeInternal(ATTRIB11, value);
    }

    /**
     * Gets the attribute value for Attrib12, using the alias name Attrib12.
     * @return the value of Attrib12
     */
    public String getAttrib12() {
        return (String) getAttributeInternal(ATTRIB12);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attrib12.
     * @param value value to set the Attrib12
     */
    public void setAttrib12(String value) {
        setAttributeInternal(ATTRIB12, value);
    }

    /**
     * Gets the attribute value for Attrib13, using the alias name Attrib13.
     * @return the value of Attrib13
     */
    public String getAttrib13() {
        return (String) getAttributeInternal(ATTRIB13);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attrib13.
     * @param value value to set the Attrib13
     */
    public void setAttrib13(String value) {
        setAttributeInternal(ATTRIB13, value);
    }

    /**
     * Gets the attribute value for Attrib14, using the alias name Attrib14.
     * @return the value of Attrib14
     */
    public String getAttrib14() {
        return (String) getAttributeInternal(ATTRIB14);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attrib14.
     * @param value value to set the Attrib14
     */
    public void setAttrib14(String value) {
        setAttributeInternal(ATTRIB14, value);
    }

    /**
     * Gets the attribute value for Attrib15, using the alias name Attrib15.
     * @return the value of Attrib15
     */
    public String getAttrib15() {
        return (String) getAttributeInternal(ATTRIB15);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attrib15.
     * @param value value to set the Attrib15
     */
    public void setAttrib15(String value) {
        setAttributeInternal(ATTRIB15, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public BigDecimal getCreatedBy() {
        return (BigDecimal) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(BigDecimal value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the value of CreationDate
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Timestamp value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the value of UpdatedBy
     */
    public BigDecimal getUpdatedBy() {
        return (BigDecimal) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedBy.
     * @param value value to set the UpdatedBy
     */
    public void setUpdatedBy(BigDecimal value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for UpdationDate, using the alias name UpdationDate.
     * @return the value of UpdationDate
     */
    public Timestamp getUpdationDate() {
        return (Timestamp) getAttributeInternal(UPDATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdationDate.
     * @param value value to set the UpdationDate
     */
    public void setUpdationDate(Timestamp value) {
        setAttributeInternal(UPDATIONDATE, value);
    }

    /**
     * Gets the attribute value for VersionNumber, using the alias name VersionNumber.
     * @return the value of VersionNumber
     */
    public BigDecimal getVersionNumber() {
        return (BigDecimal) getAttributeInternal(VERSIONNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for VersionNumber.
     * @param value value to set the VersionNumber
     */
    public void setVersionNumber(BigDecimal value) {
        setAttributeInternal(VERSIONNUMBER, value);
    }

    /**
     * Gets the attribute value for EmailAddress, using the alias name EmailAddress.
     * @return the value of EmailAddress
     */
    public String getEmailAddress() {
        return (String) getAttributeInternal(EMAILADDRESS);
    }

    /**
     * Sets <code>value</code> as the attribute value for EmailAddress.
     * @param value value to set the EmailAddress
     */
    public void setEmailAddress(String value) {
        setAttributeInternal(EMAILADDRESS, value);
    }


    /**
     * Gets the attribute value for DrivingLicExpiry, using the alias name DrivingLicExpiry.
     * @return the value of DrivingLicExpiry
     */
    public Timestamp getDrivingLicExpiry() {
        return (Timestamp) getAttributeInternal(DRIVINGLICEXPIRY);
    }

    /**
     * Sets <code>value</code> as the attribute value for DrivingLicExpiry.
     * @param value value to set the DrivingLicExpiry
     */
    public void setDrivingLicExpiry(Timestamp value) {
        setAttributeInternal(DRIVINGLICEXPIRY, value);
    }

    /**
     * Gets the attribute value for GrossPay, using the alias name GrossPay.
     * @return the value of GrossPay
     */
    public BigDecimal getGrossPay() {
        return (BigDecimal) getAttributeInternal(GROSSPAY);
    }

    /**
     * Sets <code>value</code> as the attribute value for GrossPay.
     * @param value value to set the GrossPay
     */
    public void setGrossPay(BigDecimal value) {
        setAttributeInternal(GROSSPAY, value);
    }

    /**
     * Gets the attribute value for PaymentMode, using the alias name PaymentMode.
     * @return the value of PaymentMode
     */
    public BigDecimal getPaymentMode() {
        return (BigDecimal) getAttributeInternal(PAYMENTMODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for PaymentMode.
     * @param value value to set the PaymentMode
     */
    public void setPaymentMode(BigDecimal value) {
        setAttributeInternal(PAYMENTMODE, value);
    }

    /**
     * Gets the attribute value for BankId, using the alias name BankId.
     * @return the value of BankId
     */
    public BigDecimal getBankId() {
        return (BigDecimal) getAttributeInternal(BANKID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BankId.
     * @param value value to set the BankId
     */
    public void setBankId(BigDecimal value) {
        setAttributeInternal(BANKID, value);
    }

    /**
     * Gets the attribute value for AccountNumber, using the alias name AccountNumber.
     * @return the value of AccountNumber
     */
    public String getAccountNumber() {
        return (String) getAttributeInternal(ACCOUNTNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for AccountNumber.
     * @param value value to set the AccountNumber
     */
    public void setAccountNumber(String value) {
        setAttributeInternal(ACCOUNTNUMBER, value);
    }

    /**
     * Gets the attribute value for EmployeeActive, using the alias name EmployeeActive.
     * @return the value of EmployeeActive
     */
    public String getEmployeeActive() {
        return (String) getAttributeInternal(EMPLOYEEACTIVE);
    }

    /**
     * Sets <code>value</code> as the attribute value for EmployeeActive.
     * @param value value to set the EmployeeActive
     */
    public void setEmployeeActive(String value) {
        setAttributeInternal(EMPLOYEEACTIVE, value);
    }

    /**
     * Gets the attribute value for FamilyNumber, using the alias name FamilyNumber.
     * @return the value of FamilyNumber
     */
    public String getFamilyNumber() {
        return (String) getAttributeInternal(FAMILYNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for FamilyNumber.
     * @param value value to set the FamilyNumber
     */
    public void setFamilyNumber(String value) {
        setAttributeInternal(FAMILYNUMBER, value);
    }

    /**
     * Gets the attribute value for NoticePeriodStartDate, using the alias name NoticePeriodStartDate.
     * @return the value of NoticePeriodStartDate
     */
    public Timestamp getNoticePeriodStartDate() {
        return (Timestamp) getAttributeInternal(NOTICEPERIODSTARTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for NoticePeriodStartDate.
     * @param value value to set the NoticePeriodStartDate
     */
    public void setNoticePeriodStartDate(Timestamp value) {
        setAttributeInternal(NOTICEPERIODSTARTDATE, value);
    }

    /**
     * Gets the attribute value for ResignationDate, using the alias name ResignationDate.
     * @return the value of ResignationDate
     */
    public Timestamp getResignationDate() {
        return (Timestamp) getAttributeInternal(RESIGNATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ResignationDate.
     * @param value value to set the ResignationDate
     */
    public void setResignationDate(Timestamp value) {
        setAttributeInternal(RESIGNATIONDATE, value);
    }

    /**
     * Gets the attribute value for BasicPay, using the alias name BasicPay.
     * @return the value of BasicPay
     */
    public BigDecimal getBasicPay() {
        return (BigDecimal) getAttributeInternal(BASICPAY);
    }

    /**
     * Sets <code>value</code> as the attribute value for BasicPay.
     * @param value value to set the BasicPay
     */
    public void setBasicPay(BigDecimal value) {
        setAttributeInternal(BASICPAY, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getHrJobs() {
        return (RowIterator) getAttributeInternal(HRJOBS);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getManagerIdHrEmployees() {
        return (RowIterator) getAttributeInternal(MANAGERIDHREMPLOYEES);
    }

    /**
     * @return the associated entity HrEmployeesImpl.
     */
    public HrEmployeesImpl getHrEmployees() {
        return (HrEmployeesImpl) getAttributeInternal(HREMPLOYEES);
    }

    /**
     * Sets <code>value</code> as the associated entity HrEmployeesImpl.
     */
    public void setHrEmployees(HrEmployeesImpl value) {
        setAttributeInternal(HREMPLOYEES, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getHrDepartments() {
        return (RowIterator) getAttributeInternal(HRDEPARTMENTS);
    }

    /**
     * @return the associated entity com.soltechsystem.model.sys.Entity.SysUsersImpl.
     */
    public SysUsersImpl getSysUsers() {
        return (SysUsersImpl) getAttributeInternal(SYSUSERS);
    }

    /**
     * Sets <code>value</code> as the associated entity com.soltechsystem.model.sys.Entity.SysUsersImpl.
     */
    public void setSysUsers(SysUsersImpl value) {
        setAttributeInternal(SYSUSERS, value);
    }


    /**
     * @param employeeId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal employeeId) {
        return new Key(new Object[] { employeeId });
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        String userid = (ADFContext.getCurrent()
                                   .getSessionScope()
                                   .get("userid") == null) ? "-1" : ADFContext.getCurrent()
                                                                              .getSessionScope()
                                                                              .get("userid")
                                                                              .toString();
        String usercodePrefix = (ADFContext.getCurrent()
                                   .getSessionScope()
                                   .get("EMPCODE_PREFIX") == null) ? "NULL" : ADFContext.getCurrent()
                                                                              .getSessionScope()
                                                                              .get("EMPCODE_PREFIX")
                                                                              .toString();
        
        

        switch (operation) {

        case DML_INSERT:


            setUpdatedBy(new BigDecimal(userid));
            setCreatedBy(new BigDecimal(userid));
            
            setEmployeeCode(usercodePrefix+""+getEmployeeId());
//            if (getUserCreated().equals("Y"))
//                assignBasicProfile();
            break;
        case DML_UPDATE:
            createEmpHistory();
            setUpdatedBy(new BigDecimal(userid));

        }
        super.doDML(operation, e);
    }
    private void createEmpHistory() {

        CallableStatement cst = null;
        try {
            cst = getDBTransaction().createCallableStatement("{call sthrms.create_employee_history(?)}", 0);

            cst.setInt(1, getEmployeeId().intValue());

            cst.executeUpdate();
            System.out.println(cst.getString(1));


        } catch (Exception ex) {
            ex.printStackTrace();
            

        }
    }
    
    public void assignBasicProfile() {

        CallableStatement cst = null;
        try {
            cst = getDBTransaction().createCallableStatement("{call sthrms.sthrms_utils.assign_basic_profile(?)}", 0);

            cst.setInt(1, getEmployeeId().intValue());

            cst.executeUpdate();
            System.out.println(cst.getString(1));


        } catch (Exception ex) {
            ex.printStackTrace();
            

        }
    }
}

