package com.soltechsystem.model.prl.ViewObject;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Dec 30 21:30:51 PKT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PayrollRunOptionImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public PayrollRunOptionImpl() {
    }
}

