package com.soltechsystem.model.prl.ViewObject;

import com.soltechsystem.model.prl.Entity.PrlAllowDeductTrxImpl;

import com.soltechsystem.model.prl.ViewObject.common.PrlAllowDeductTrxViewRow;

import java.math.BigDecimal;

import java.sql.CallableStatement;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.Timestamp;

import java.sql.Types;

import oracle.jbo.RowSet;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Dec 30 10:42:47 PKT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PrlAllowDeductTrxViewRowImpl extends ViewRowImpl implements PrlAllowDeductTrxViewRow {


    public static final int ENTITY_PRLALLOWDEDUCTTRX = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        TrxId,
        EmployeeId,
        StartDate,
        EndDate,
        CreatedBy,
        UpdatedBy,
        CreationDate,
        UpdationDate,
        VersionNumber,
        AllowenceDeductionName,
        DeductionType,
        TrxType,
        Val,
        ValueType,
        ValueTypeMeaning,
        TrxTypeMeaning,
        DeductionTypeMeaning,
        AllowDeductId,
        Active,
        StartDateType,
        PRLAM_AllowDeductList1_1,
        HRAM_StartDatesList1_1;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int TRXID = AttributesEnum.TrxId.index();
    public static final int EMPLOYEEID = AttributesEnum.EmployeeId.index();
    public static final int STARTDATE = AttributesEnum.StartDate.index();
    public static final int ENDDATE = AttributesEnum.EndDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int UPDATIONDATE = AttributesEnum.UpdationDate.index();
    public static final int VERSIONNUMBER = AttributesEnum.VersionNumber.index();
    public static final int ALLOWENCEDEDUCTIONNAME = AttributesEnum.AllowenceDeductionName.index();
    public static final int DEDUCTIONTYPE = AttributesEnum.DeductionType.index();
    public static final int TRXTYPE = AttributesEnum.TrxType.index();
    public static final int VAL = AttributesEnum.Val.index();
    public static final int VALUETYPE = AttributesEnum.ValueType.index();
    public static final int VALUETYPEMEANING = AttributesEnum.ValueTypeMeaning.index();
    public static final int TRXTYPEMEANING = AttributesEnum.TrxTypeMeaning.index();
    public static final int DEDUCTIONTYPEMEANING = AttributesEnum.DeductionTypeMeaning.index();
    public static final int ALLOWDEDUCTID = AttributesEnum.AllowDeductId.index();
    public static final int ACTIVE = AttributesEnum.Active.index();
    public static final int STARTDATETYPE = AttributesEnum.StartDateType.index();
    public static final int PRLAM_ALLOWDEDUCTLIST1_1 = AttributesEnum.PRLAM_AllowDeductList1_1.index();
    public static final int HRAM_STARTDATESLIST1_1 = AttributesEnum.HRAM_StartDatesList1_1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PrlAllowDeductTrxViewRowImpl() {
    }

    /**
     * Gets PrlAllowDeductTrx entity object.
     * @return the PrlAllowDeductTrx
     */
    public PrlAllowDeductTrxImpl getPrlAllowDeductTrx() {
        return (PrlAllowDeductTrxImpl) getEntity(ENTITY_PRLALLOWDEDUCTTRX);
    }

    /**
     * Gets the attribute value for TRX_ID using the alias name TrxId.
     * @return the TRX_ID
     */
    public BigDecimal getTrxId() {
        return (BigDecimal) getAttributeInternal(TRXID);
    }

    /**
     * Sets <code>value</code> as attribute value for TRX_ID using the alias name TrxId.
     * @param value value to set the TRX_ID
     */
    public void setTrxId(BigDecimal value) {
        setAttributeInternal(TRXID, value);
    }

    /**
     * Gets the attribute value for EMPLOYEE_ID using the alias name EmployeeId.
     * @return the EMPLOYEE_ID
     */
    public BigDecimal getEmployeeId() {
        return (BigDecimal) getAttributeInternal(EMPLOYEEID);
    }

    /**
     * Sets <code>value</code> as attribute value for EMPLOYEE_ID using the alias name EmployeeId.
     * @param value value to set the EMPLOYEE_ID
     */
    public void setEmployeeId(BigDecimal value) {
        setAttributeInternal(EMPLOYEEID, value);
    }

    /**
     * Gets the attribute value for START_DATE using the alias name StartDate.
     * @return the START_DATE
     */
    public Timestamp getStartDate() {
        return (Timestamp) getAttributeInternal(STARTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for START_DATE using the alias name StartDate.
     * @param value value to set the START_DATE
     */
    public void setStartDate(Timestamp value) {
        setAttributeInternal(STARTDATE, value);
    }

    /**
     * Gets the attribute value for END_DATE using the alias name EndDate.
     * @return the END_DATE
     */
    public Timestamp getEndDate() {
        return (Timestamp) getAttributeInternal(ENDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for END_DATE using the alias name EndDate.
     * @param value value to set the END_DATE
     */
    public void setEndDate(Timestamp value) {
        setAttributeInternal(ENDDATE, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public BigDecimal getCreatedBy() {
        return (BigDecimal) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(BigDecimal value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for UPDATED_BY using the alias name UpdatedBy.
     * @return the UPDATED_BY
     */
    public BigDecimal getUpdatedBy() {
        return (BigDecimal) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for UPDATED_BY using the alias name UpdatedBy.
     * @param value value to set the UPDATED_BY
     */
    public void setUpdatedBy(BigDecimal value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Gets the attribute value for UPDATION_DATE using the alias name UpdationDate.
     * @return the UPDATION_DATE
     */
    public Timestamp getUpdationDate() {
        return (Timestamp) getAttributeInternal(UPDATIONDATE);
    }

    /**
     * Gets the attribute value for VERSION_NUMBER using the alias name VersionNumber.
     * @return the VERSION_NUMBER
     */
    public BigDecimal getVersionNumber() {
        return (BigDecimal) getAttributeInternal(VERSIONNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for VERSION_NUMBER using the alias name VersionNumber.
     * @param value value to set the VERSION_NUMBER
     */
    public void setVersionNumber(BigDecimal value) {
        setAttributeInternal(VERSIONNUMBER, value);
    }

    /**
     * Gets the attribute value for ALLOWENCE_DEDUCTION_NAME using the alias name AllowenceDeductionName.
     * @return the ALLOWENCE_DEDUCTION_NAME
     */
    public String getAllowenceDeductionName() {
        return (String) getAttributeInternal(ALLOWENCEDEDUCTIONNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for ALLOWENCE_DEDUCTION_NAME using the alias name AllowenceDeductionName.
     * @param value value to set the ALLOWENCE_DEDUCTION_NAME
     */
    public void setAllowenceDeductionName(String value) {
        setAttributeInternal(ALLOWENCEDEDUCTIONNAME, value);
    }

    /**
     * Gets the attribute value for DEDUCTION_TYPE using the alias name DeductionType.
     * @return the DEDUCTION_TYPE
     */
    public BigDecimal getDeductionType() {
        return (BigDecimal) getAttributeInternal(DEDUCTIONTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for DEDUCTION_TYPE using the alias name DeductionType.
     * @param value value to set the DEDUCTION_TYPE
     */
    public void setDeductionType(BigDecimal value) {
        setAttributeInternal(DEDUCTIONTYPE, value);
    }

    /**
     * Gets the attribute value for TRX_TYPE using the alias name TrxType.
     * @return the TRX_TYPE
     */
    public BigDecimal getTrxType() {
        return (BigDecimal) getAttributeInternal(TRXTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for TRX_TYPE using the alias name TrxType.
     * @param value value to set the TRX_TYPE
     */
    public void setTrxType(BigDecimal value) {
        setAttributeInternal(TRXTYPE, value);
    }

    /**
     * Gets the attribute value for VAL using the alias name Val.
     * @return the VAL
     */
    public BigDecimal getVal() {
        return (BigDecimal) getAttributeInternal(VAL);
    }

    /**
     * Sets <code>value</code> as attribute value for VAL using the alias name Val.
     * @param value value to set the VAL
     */
    public void setVal(BigDecimal value) {
        setAttributeInternal(VAL, value);
    }

    /**
     * Gets the attribute value for VALUE_TYPE using the alias name ValueType.
     * @return the VALUE_TYPE
     */
    public BigDecimal getValueType() {
        return (BigDecimal) getAttributeInternal(VALUETYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for VALUE_TYPE using the alias name ValueType.
     * @param value value to set the VALUE_TYPE
     */
    public void setValueType(BigDecimal value) {
        setAttributeInternal(VALUETYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ValueTypeMeaning.
     * @return the ValueTypeMeaning
     */
    public String getValueTypeMeaning() {
        return (String) getAttributeInternal(VALUETYPEMEANING);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ValueTypeMeaning.
     * @param value value to set the  ValueTypeMeaning
     */
    public void setValueTypeMeaning(String value) {
        setAttributeInternal(VALUETYPEMEANING, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TrxTypeMeaning.
     * @return the TrxTypeMeaning
     */
    public String getTrxTypeMeaning() {
        return (String) getAttributeInternal(TRXTYPEMEANING);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TrxTypeMeaning.
     * @param value value to set the  TrxTypeMeaning
     */
    public void setTrxTypeMeaning(String value) {
        setAttributeInternal(TRXTYPEMEANING, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DeductionTypeMeaning.
     * @return the DeductionTypeMeaning
     */
    public String getDeductionTypeMeaning() {
        return (String) getAttributeInternal(DEDUCTIONTYPEMEANING);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DeductionTypeMeaning.
     * @param value value to set the  DeductionTypeMeaning
     */
    public void setDeductionTypeMeaning(String value) {
        setAttributeInternal(DEDUCTIONTYPEMEANING, value);
    }

    /**
     * Gets the attribute value for ALLOW_DEDUCT_ID using the alias name AllowDeductId.
     * @return the ALLOW_DEDUCT_ID
     */
    public BigDecimal getAllowDeductId() {
        return (BigDecimal) getAttributeInternal(ALLOWDEDUCTID);
    }

    /**
     * Sets <code>value</code> as attribute value for ALLOW_DEDUCT_ID using the alias name AllowDeductId.
     * @param value value to set the ALLOW_DEDUCT_ID
     */
    public void setAllowDeductId(BigDecimal value) {
        setAttributeInternal(ALLOWDEDUCTID, value);
    }

    /**
     * Gets the attribute value for ACTIVE using the alias name Active.
     * @return the ACTIVE
     */
    public String getActive() {
        return (String) getAttributeInternal(ACTIVE);
    }

    /**
     * Sets <code>value</code> as attribute value for ACTIVE using the alias name Active.
     * @param value value to set the ACTIVE
     */
    public void setActive(String value) {
        setAttributeInternal(ACTIVE, value);
    }

    /**
     * Gets the attribute value for START_DATE_TYPE using the alias name StartDateType.
     * @return the START_DATE_TYPE
     */
    public BigDecimal getStartDateType() {
        return (BigDecimal) getAttributeInternal(STARTDATETYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for START_DATE_TYPE using the alias name StartDateType.
     * @param value value to set the START_DATE_TYPE
     */
    public void setStartDateType(BigDecimal value) {
        setAttributeInternal(STARTDATETYPE, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PRLAM_AllowDeductList1_1.
     */
    public RowSet getPRLAM_AllowDeductList1_1() {
        return (RowSet) getAttributeInternal(PRLAM_ALLOWDEDUCTLIST1_1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> HRAM_StartDatesList1_1.
     */
    public RowSet getHRAM_StartDatesList1_1() {
        return (RowSet) getAttributeInternal(HRAM_STARTDATESLIST1_1);
    }

    public Date getDate() {
        CallableStatement pst;
        try {
            pst = getDBTransaction().createCallableStatement("call ? := sthrms.sthrms_utils.getDate(?,?)", 0);
            pst.registerOutParameter(1, Types.DATE);
            pst.setInt(2, getStartDateType().intValue());
            pst.setInt(3, getEmployeeId().intValue());
            pst.executeQuery();

            return pst.getDate(1);


        } catch (Exception ex) {
            ex.printStackTrace();
            return null;
        }
    }

}

