package com.soltechsystem.model.prl.am;

import com.soltechsystem.model.prl.ViewObject.PayrollRunOptionImpl;
import com.soltechsystem.model.prl.am.common.PRLAM;

import java.sql.CallableStatement;
import java.sql.Date;

import java.sql.PreparedStatement;

import java.sql.ResultSet;

import java.sql.Types;

import oracle.adf.share.ADFContext;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 20 21:33:44 PKT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PRLAMImpl extends ApplicationModuleImpl implements PRLAM {
    /**
     * This is the default constructor (do not remove).
     */
    public PRLAMImpl() {
    }

    /**
     * Container's getter for PrlAllowenceDeductionView1.
     * @return PrlAllowenceDeductionView1
     */
    public ViewObjectImpl getPrlAllowenceDeductionView1() {
        return (ViewObjectImpl) findViewObject("PrlAllowenceDeductionView1");
    }

    /**
     * Container's getter for DeductionTypeList1.
     * @return DeductionTypeList1
     */
    public ViewObjectImpl getDeductionTypeList1() {
        return (ViewObjectImpl) findViewObject("DeductionTypeList1");
    }

    /**
     * Container's getter for AllowDeductValueTypeList1.
     * @return AllowDeductValueTypeList1
     */
    public ViewObjectImpl getAllowDeductValueTypeList1() {
        return (ViewObjectImpl) findViewObject("AllowDeductValueTypeList1");
    }

    /**
     * Container's getter for AllowDeductLineTypeList1.
     * @return AllowDeductLineTypeList1
     */
    public ViewObjectImpl getAllowDeductLineTypeList1() {
        return (ViewObjectImpl) findViewObject("AllowDeductLineTypeList1");
    }

    /**
     * Container's getter for PrlGradeHeaderView1.
     * @return PrlGradeHeaderView1
     */
    public ViewObjectImpl getPrlGradeHeaderView1() {
        return (ViewObjectImpl) findViewObject("PrlGradeHeaderView1");
    }

    /**
     * Container's getter for PrlGradeLinesView1.
     * @return PrlGradeLinesView1
     */
    public ViewObjectImpl getPrlGradeLinesView1() {
        return (ViewObjectImpl) findViewObject("PrlGradeLinesView1");
    }

    /**
     * Container's getter for AllowDeductList1.
     * @return AllowDeductList1
     */
    public ViewObjectImpl getAllowDeductList1() {
        return (ViewObjectImpl) findViewObject("AllowDeductList1");
    }

    /**
     * Container's getter for PrlSpecialAllowDeductView1.
     * @return PrlSpecialAllowDeductView1
     */
    public ViewObjectImpl getPrlSpecialAllowDeductView1() {
        return (ViewObjectImpl) findViewObject("PrlSpecialAllowDeductView1");
    }

    /**
     * Container's getter for MonthsList1.
     * @return MonthsList1
     */
    public ViewObjectImpl getMonthsList1() {
        return (ViewObjectImpl) findViewObject("MonthsList1");
    }

    /**
     * Container's getter for SpecialAllowDeductList1.
     * @return SpecialAllowDeductList1
     */
    public ViewObjectImpl getSpecialAllowDeductList1() {
        return (ViewObjectImpl) findViewObject("SpecialAllowDeductList1");
    }

    /**
     * Container's getter for HrEmployeeLeavesView1.
     * @return HrEmployeeLeavesView1
     */
    public ViewObjectImpl getHrEmployeeLeavesView1() {
        return (ViewObjectImpl) findViewObject("HrEmployeeLeavesView1");
    }

    /**
     * Container's getter for LeaveTypeList1.
     * @return LeaveTypeList1
     */
    public ViewObjectImpl getLeaveTypeList1() {
        return (ViewObjectImpl) findViewObject("LeaveTypeList1");
    }

    /**
     * Container's getter for PrlLoanView1.
     * @return PrlLoanView1
     */
    public ViewObjectImpl getPrlLoanView1() {
        return (ViewObjectImpl) findViewObject("PrlLoanView1");
    }

    /**
     * Container's getter for LoanTypeList1.
     * @return LoanTypeList1
     */
    public ViewObjectImpl getLoanTypeList1() {
        return (ViewObjectImpl) findViewObject("LoanTypeList1");
    }

    /**
     * Container's getter for PrlAdvanceSalaryView1.
     * @return PrlAdvanceSalaryView1
     */
    public ViewObjectImpl getPrlAdvanceSalaryView1() {
        return (ViewObjectImpl) findViewObject("PrlAdvanceSalaryView1");
    }

    /**
     * Container's getter for PrlAllowDeductTrxView1.
     * @return PrlAllowDeductTrxView1
     */
    public ViewObjectImpl getPrlAllowDeductTrxView1() {
        return (ViewObjectImpl) findViewObject("PrlAllowDeductTrxView1");
    }

    /**
     * Container's getter for PrlGradeList1.
     * @return PrlGradeList1
     */
    public ViewObjectImpl getPrlGradeList1() {
        return (ViewObjectImpl) findViewObject("PrlGradeList1");
    }

    /**
     * Container's getter for GradeAllowDeductLink1.
     * @return GradeAllowDeductLink1
     */
    public ViewLinkImpl getGradeAllowDeductLink1() {
        return (ViewLinkImpl) findViewLink("GradeAllowDeductLink1");
    }

    public String generateSalary(Date pFrom, int activeMonthID, int pEmpType, int pDepartmentID, int pJobID, int pOrgID,
                               int branch, int pEmpID) {

        

        CallableStatement cst = null;
        PreparedStatement pst = null;
        String userid = (ADFContext.getCurrent()
                                   .getSessionScope()
                                   .get("userid") == null) ? "-1" : ADFContext.getCurrent()
                                                                              .getSessionScope()
                                                                              .get("userid")
                                                                              .toString();
        String result = null;
        
        Date pf = null;
        try {
            pst = getDBTransaction().createPreparedStatement("select start_Date pfrom from prl_salary_period_lines where active = 'Y'", 0);
            ResultSet rs = pst.executeQuery();
            rs.next();
            pf = rs.getDate("pfrom");
        } catch (Exception ex) {
            ex.printStackTrace();
        }


        try {
            cst = getDBTransaction().createCallableStatement("{call sthrms.prl_generate_salary(?,?,?,?,?,?,?,?,?)}", 0);

            cst.setDate(1, pf);
            cst.setInt(2, pEmpType);
            cst.setInt(3, pDepartmentID);
            cst.setInt(4, pJobID);
            cst.setInt(5, 1);
            cst.setInt(6, pOrgID);
            cst.setInt(7, branch);
            cst.setInt(8, Integer.parseInt(userid));
            cst.registerOutParameter(9, Types.VARCHAR);
            cst.executeUpdate();

            result = cst.getString(9);
            
        } catch (Exception ex) {
            return "";
        }
        return result;

    }

    public int payrollExist(){
        
        Date pf = null;
        PreparedStatement pst = null;
        try {
            pst = getDBTransaction().createPreparedStatement("select start_Date pfrom from prl_salary_period_lines where active = 'Y'", 0);
            ResultSet rs = pst.executeQuery();
            rs.next();
            pf = rs.getDate("pfrom");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
        
        CallableStatement cst = null;
        int n = -1;
        try {
            cst = getDBTransaction().createCallableStatement("{call ? := sthrms.prl_payroll_exist(?)}", 0);
            cst.registerOutParameter(1, Types.INTEGER);
            cst.setDate(2, pf);
            cst.executeUpdate();
            n = cst.getInt(1);

        } catch (Exception ex) {
            n = -1;
        }
        
        return n;
    }
    public void generateSalPeriod(Date d1, int headerID) {
        String userid = (ADFContext.getCurrent()
                                   .getSessionScope()
                                   .get("userid") == null) ? "-1" : ADFContext.getCurrent()
                                                                              .getSessionScope()
                                                                              .get("userid")
                                                                              .toString();
        CallableStatement cst = null;
        try {
            cst = getDBTransaction().createCallableStatement("{call sthrms.prl_generate_salary_period(?,?,?)}", 0);
            cst.setDate(1, d1);
            cst.setInt(2, headerID);
            cst.setInt(3, Integer.parseInt(userid));
            cst.executeUpdate();


        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
        getDBTransaction().commit();

    }

    public void assignGrade(int employeeID, int gradeID) {
        CallableStatement cst = null;
        String userid = (ADFContext.getCurrent()
                                   .getSessionScope()
                                   .get("userid") == null) ? "-1" : ADFContext.getCurrent()
                                                                              .getSessionScope()
                                                                              .get("userid")
                                                                              .toString();


        try {
            cst = getDBTransaction().createCallableStatement("{call sthrms.sthrms_utils.assign_grade(?,?,?)}", 0);
            cst.setInt(1, employeeID);
            cst.setInt(2, gradeID);
            cst.setInt(3, Integer.parseInt(userid));
            cst.executeUpdate();


        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * Container's getter for PrlSalaryPeriodHeaderView1.
     * @return PrlSalaryPeriodHeaderView1
     */
    public ViewObjectImpl getPrlSalaryPeriodHeaderView1() {
        return (ViewObjectImpl) findViewObject("PrlSalaryPeriodHeaderView1");
    }


    /**
     * Container's getter for PrlTaxSlabView1.
     * @return PrlTaxSlabView1
     */
    public ViewObjectImpl getPrlTaxSlabView1() {
        return (ViewObjectImpl) findViewObject("PrlTaxSlabView1");
    }

    /**
     * Container's getter for PrlPayrollRunView1.
     * @return PrlPayrollRunView1
     */
    public ViewObjectImpl getPrlPayrollRunView1() {
        return (ViewObjectImpl) findViewObject("PrlPayrollRunView1");
    }

    /**
     * Container's getter for HrEmpOvertimeView1.
     * @return HrEmpOvertimeView1
     */
    public ViewObjectImpl getHrEmpOvertimeView1() {
        return (ViewObjectImpl) findViewObject("HrEmpOvertimeView1");
    }

    /**
     * Container's getter for PrlBanksView1.
     * @return PrlBanksView1
     */
    public ViewObjectImpl getPrlBanksView1() {
        return (ViewObjectImpl) findViewObject("PrlBanksView1");
    }

    /**
     * Container's getter for MonthCodeList1.
     * @return MonthCodeList1
     */
    public ViewObjectImpl getMonthCodeList1() {
        return (ViewObjectImpl) findViewObject("MonthCodeList1");
    }

    /**
     * Container's getter for PayrollRunParamForm1.
     * @return PayrollRunParamForm1
     */
    public ViewObjectImpl getPayrollRunParamForm1() {
        return (ViewObjectImpl) findViewObject("PayrollRunParamForm1");
    }

    /**
     * Container's getter for PayrollRunOption1.
     * @return PayrollRunOption1
     */
    public PayrollRunOptionImpl getPayrollRunOption1() {
        return (PayrollRunOptionImpl) findViewObject("PayrollRunOption1");
    }

    /**
     * Container's getter for PrlSalaryPeriodLinesView1.
     * @return PrlSalaryPeriodLinesView1
     */
    public ViewObjectImpl getPrlSalaryPeriodLinesView1() {
        return (ViewObjectImpl) findViewObject("PrlSalaryPeriodLinesView1");
    }

    /**
     * Container's getter for PrlSalaryPeriodLink1.
     * @return PrlSalaryPeriodLink1
     */
    public ViewLinkImpl getPrlSalaryPeriodLink1() {
        return (ViewLinkImpl) findViewLink("PrlSalaryPeriodLink1");
    }
}

