package com.soltechsystem.model.hr.am.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 22 10:26:57 PKT 2018
// ---------------------------------------------------------------------
public interface HRAM extends ApplicationModule {
    String login(String username, String password);

    void leaveAction(int employeeID, int leaveID, String action, String leaveType, int total);

    int getEmployeeID(int userid);
}

