package com.soltechsystem.model.tms.Entity;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.adf.share.ADFContext;

import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat May 04 17:47:02 PKT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeeInoutInterfaceImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        InoutInterfaceId,
        EmployeeId,
        InoutDate,
        LogTime,
        Terminal,
        CreatedBy,
        CreationDate,
        UpdatedBy,
        UpdationDate,
        VersionNumber;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int INOUTINTERFACEID = AttributesEnum.InoutInterfaceId.index();
    public static final int EMPLOYEEID = AttributesEnum.EmployeeId.index();
    public static final int INOUTDATE = AttributesEnum.InoutDate.index();
    public static final int LOGTIME = AttributesEnum.LogTime.index();
    public static final int TERMINAL = AttributesEnum.Terminal.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int UPDATIONDATE = AttributesEnum.UpdationDate.index();
    public static final int VERSIONNUMBER = AttributesEnum.VersionNumber.index();

    /**
     * This is the default constructor (do not remove).
     */
    public EmployeeInoutInterfaceImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.soltechsystem.model.tms.Entity.EmployeeInoutInterface");
    }


    /**
     * Gets the attribute value for InoutInterfaceId, using the alias name InoutInterfaceId.
     * @return the value of InoutInterfaceId
     */
    public BigDecimal getInoutInterfaceId() {
        return (BigDecimal) getAttributeInternal(INOUTINTERFACEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for InoutInterfaceId.
     * @param value value to set the InoutInterfaceId
     */
    public void setInoutInterfaceId(BigDecimal value) {
        setAttributeInternal(INOUTINTERFACEID, value);
    }

    /**
     * Gets the attribute value for EmployeeId, using the alias name EmployeeId.
     * @return the value of EmployeeId
     */
    public BigDecimal getEmployeeId() {
        return (BigDecimal) getAttributeInternal(EMPLOYEEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for EmployeeId.
     * @param value value to set the EmployeeId
     */
    public void setEmployeeId(BigDecimal value) {
        setAttributeInternal(EMPLOYEEID, value);
    }

    /**
     * Gets the attribute value for InoutDate, using the alias name InoutDate.
     * @return the value of InoutDate
     */
    public Timestamp getInoutDate() {
        return (Timestamp) getAttributeInternal(INOUTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for InoutDate.
     * @param value value to set the InoutDate
     */
    public void setInoutDate(Timestamp value) {
        setAttributeInternal(INOUTDATE, value);
    }

    /**
     * Gets the attribute value for LogTime, using the alias name LogTime.
     * @return the value of LogTime
     */
    public Timestamp getLogTime() {
        return (Timestamp) getAttributeInternal(LOGTIME);
    }

    /**
     * Sets <code>value</code> as the attribute value for LogTime.
     * @param value value to set the LogTime
     */
    public void setLogTime(Timestamp value) {
        setAttributeInternal(LOGTIME, value);
    }

    /**
     * Gets the attribute value for Terminal, using the alias name Terminal.
     * @return the value of Terminal
     */
    public String getTerminal() {
        return (String) getAttributeInternal(TERMINAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for Terminal.
     * @param value value to set the Terminal
     */
    public void setTerminal(String value) {
        setAttributeInternal(TERMINAL, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public BigDecimal getCreatedBy() {
        return (BigDecimal) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(BigDecimal value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the value of CreationDate
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Timestamp value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the value of UpdatedBy
     */
    public BigDecimal getUpdatedBy() {
        return (BigDecimal) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedBy.
     * @param value value to set the UpdatedBy
     */
    public void setUpdatedBy(BigDecimal value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for UpdationDate, using the alias name UpdationDate.
     * @return the value of UpdationDate
     */
    public Timestamp getUpdationDate() {
        return (Timestamp) getAttributeInternal(UPDATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdationDate.
     * @param value value to set the UpdationDate
     */
    public void setUpdationDate(Timestamp value) {
        setAttributeInternal(UPDATIONDATE, value);
    }

    /**
     * Gets the attribute value for VersionNumber, using the alias name VersionNumber.
     * @return the value of VersionNumber
     */
    public BigDecimal getVersionNumber() {
        return (BigDecimal) getAttributeInternal(VERSIONNUMBER);
    }


    /**
     * Sets <code>value</code> as the attribute value for VersionNumber.
     * @param value value to set the VersionNumber
     */
    public void setVersionNumber(BigDecimal value) {
        setAttributeInternal(VERSIONNUMBER, value);
    }

    /**
     * @param inoutInterfaceId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal inoutInterfaceId) {
        return new Key(new Object[] { inoutInterfaceId });
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        String userid = (ADFContext.getCurrent()
                                   .getSessionScope()
                                   .get("userid") == null) ? "-1" : ADFContext.getCurrent()
                                                                              .getSessionScope()
                                                                              .get("userid")
                                                                              .toString();


        switch (operation) {

        case DML_INSERT:


            setUpdatedBy(new BigDecimal(userid));
            setCreatedBy(new BigDecimal(userid));
        
            break;
        case DML_UPDATE:
            setUpdatedBy(new BigDecimal(userid));

        }
        super.doDML(operation, e);
    }
}

