package com.soltechsystem.model.tms.Entity;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Apr 28 13:38:39 PKT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeeShiftsImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        ShiftId,
        ShiftCode,
        ShiftStartTime,
        ShiftEndTime,
        CreatedBy,
        CreationDate,
        UpdatedBy,
        UpdationDate,
        VersionNumber,
        ShiftDesc;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int SHIFTID = AttributesEnum.ShiftId.index();
    public static final int SHIFTCODE = AttributesEnum.ShiftCode.index();
    public static final int SHIFTSTARTTIME = AttributesEnum.ShiftStartTime.index();
    public static final int SHIFTENDTIME = AttributesEnum.ShiftEndTime.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int UPDATIONDATE = AttributesEnum.UpdationDate.index();
    public static final int VERSIONNUMBER = AttributesEnum.VersionNumber.index();
    public static final int SHIFTDESC = AttributesEnum.ShiftDesc.index();

    /**
     * This is the default constructor (do not remove).
     */
    public EmployeeShiftsImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.soltechsystem.model.tms.Entity.EmployeeShifts");
    }


    /**
     * Gets the attribute value for ShiftId, using the alias name ShiftId.
     * @return the value of ShiftId
     */
    public BigDecimal getShiftId() {
        return (BigDecimal) getAttributeInternal(SHIFTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShiftId.
     * @param value value to set the ShiftId
     */
    public void setShiftId(BigDecimal value) {
        setAttributeInternal(SHIFTID, value);
    }

    /**
     * Gets the attribute value for ShiftCode, using the alias name ShiftCode.
     * @return the value of ShiftCode
     */
    public String getShiftCode() {
        return (String) getAttributeInternal(SHIFTCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShiftCode.
     * @param value value to set the ShiftCode
     */
    public void setShiftCode(String value) {
        setAttributeInternal(SHIFTCODE, value);
    }

    /**
     * Gets the attribute value for ShiftStartTime, using the alias name ShiftStartTime.
     * @return the value of ShiftStartTime
     */
    public String getShiftStartTime() {
        return (String) getAttributeInternal(SHIFTSTARTTIME);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShiftStartTime.
     * @param value value to set the ShiftStartTime
     */
    public void setShiftStartTime(String value) {
        setAttributeInternal(SHIFTSTARTTIME, value);
    }

    /**
     * Gets the attribute value for ShiftEndTime, using the alias name ShiftEndTime.
     * @return the value of ShiftEndTime
     */
    public String getShiftEndTime() {
        return (String) getAttributeInternal(SHIFTENDTIME);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShiftEndTime.
     * @param value value to set the ShiftEndTime
     */
    public void setShiftEndTime(String value) {
        setAttributeInternal(SHIFTENDTIME, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public BigDecimal getCreatedBy() {
        return (BigDecimal) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(BigDecimal value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the value of CreationDate
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }


    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the value of UpdatedBy
     */
    public BigDecimal getUpdatedBy() {
        return (BigDecimal) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedBy.
     * @param value value to set the UpdatedBy
     */
    public void setUpdatedBy(BigDecimal value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for UpdationDate, using the alias name UpdationDate.
     * @return the value of UpdationDate
     */
    public Timestamp getUpdationDate() {
        return (Timestamp) getAttributeInternal(UPDATIONDATE);
    }


    /**
     * Gets the attribute value for VersionNumber, using the alias name VersionNumber.
     * @return the value of VersionNumber
     */
    public BigDecimal getVersionNumber() {
        return (BigDecimal) getAttributeInternal(VERSIONNUMBER);
    }


    /**
     * Gets the attribute value for ShiftDesc, using the alias name ShiftDesc.
     * @return the value of ShiftDesc
     */
    public String getShiftDesc() {
        return (String) getAttributeInternal(SHIFTDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShiftDesc.
     * @param value value to set the ShiftDesc
     */
    public void setShiftDesc(String value) {
        setAttributeInternal(SHIFTDESC, value);
    }

    /**
     * @param shiftId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal shiftId) {
        return new Key(new Object[] { shiftId });
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }
}

