package com.soltechsystem.model.sys.am;

import com.soltechsystem.model.sys.am.common.SysAM;

import java.sql.PreparedStatement;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Dec 15 16:08:42 PKT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SysAMImpl extends ApplicationModuleImpl implements SysAM {
    /**
     * This is the default constructor (do not remove).
     */
    public SysAMImpl() {
    }

    /**
     * Container's getter for VOMainMenu1.
     * @return VOMainMenu1
     */
    public ViewObjectImpl getVOMainMenu1() {
        return (ViewObjectImpl) findViewObject("VOMainMenu1");
    }

    /**
     * Container's getter for SysUsersView1.
     * @return SysUsersView1
     */
    public ViewObjectImpl getSysUsersView1() {
        return (ViewObjectImpl) findViewObject("SysUsersView1");
    }

    /**
     * Container's getter for LOVEmployees1.
     * @return LOVEmployees1
     */
    public ViewObjectImpl getLOVEmployees1() {
        return (ViewObjectImpl) findViewObject("LOVEmployees1");
    }

    /**
     * Container's getter for SysUserRoleView1.
     * @return SysUserRoleView1
     */
    public ViewObjectImpl getSysUserRoleView1() {
        return (ViewObjectImpl) findViewObject("SysUserRoleView1");
    }

    /**
     * Container's getter for LOVProfileMaster1.
     * @return LOVProfileMaster1
     */
    public ViewObjectImpl getLOVProfileMaster1() {
        return (ViewObjectImpl) findViewObject("LOVProfileMaster1");
    }

    /**
     * Container's getter for SysUserRoleDetailView1.
     * @return SysUserRoleDetailView1
     */
    public ViewObjectImpl getSysUserRoleDetailView1() {
        return (ViewObjectImpl) findViewObject("SysUserRoleDetailView1");
    }

    /**
     * Container's getter for SysProfileAssignmentHeaderView1.
     * @return SysProfileAssignmentHeaderView1
     */
    public ViewObjectImpl getSysProfileAssignmentHeaderView1() {
        return (ViewObjectImpl) findViewObject("SysProfileAssignmentHeaderView1");
    }

    /**
     * Container's getter for SysProfileAssignmentLinesView1.
     * @return SysProfileAssignmentLinesView1
     */
    public ViewObjectImpl getSysProfileAssignmentLinesView1() {
        return (ViewObjectImpl) findViewObject("SysProfileAssignmentLinesView1");
    }

    /**
     * Container's getter for LOVUsers1.
     * @return LOVUsers1
     */
    public ViewObjectImpl getLOVUsers1() {
        return (ViewObjectImpl) findViewObject("LOVUsers1");
    }

    /**
     * Container's getter for LOVYesNo1.
     * @return LOVYesNo1
     */
    public ViewObjectImpl getLOVYesNo1() {
        return (ViewObjectImpl) findViewObject("LOVYesNo1");
    }

    /**
     * Container's getter for SysUserRoleAsgtView1.
     * @return SysUserRoleAsgtView1
     */
    public ViewObjectImpl getSysUserRoleAsgtView1() {
        return (ViewObjectImpl) findViewObject("SysUserRoleAsgtView1");
    }

    /**
     * Container's getter for SysUserRoleViewLOV.
     * @return SysUserRoleViewLOV
     */
    public ViewObjectImpl getSysUserRoleViewLOV() {
        return (ViewObjectImpl) findViewObject("SysUserRoleViewLOV");
    }

    /**
     * Container's getter for SysUserRoleAsgtDetailView1.
     * @return SysUserRoleAsgtDetailView1
     */
    public ViewObjectImpl getSysUserRoleAsgtDetailView1() {
        return (ViewObjectImpl) findViewObject("SysUserRoleAsgtDetailView1");
    }

    /**
     * Container's getter for UserRoleBasedAccessProfiles1.
     * @return UserRoleBasedAccessProfiles1
     */
    public ViewObjectImpl getUserRoleBasedAccessProfiles1() {
        return (ViewObjectImpl) findViewObject("UserRoleBasedAccessProfiles1");
    }

    /**
     * Container's getter for HrLookupContextView1.
     * @return HrLookupContextView1
     */
    public ViewObjectImpl getHrLookupContextView1() {
        return (ViewObjectImpl) findViewObject("HrLookupContextView1");
    }

    /**
     * Container's getter for HrLookupValuesView1.
     * @return HrLookupValuesView1
     */
    public ViewObjectImpl getHrLookupValuesView1() {
        return (ViewObjectImpl) findViewObject("HrLookupValuesView1");
    }

    /**
     * Container's getter for SysFilesView1.
     * @return SysFilesView1
     */
    public ViewObjectImpl getSysFilesView1() {
        return (ViewObjectImpl) findViewObject("SysFilesView1");
    }

    /**
     * Container's getter for RoleHeaderDetailLink1.
     * @return RoleHeaderDetailLink1
     */
    public ViewLinkImpl getRoleHeaderDetailLink1() {
        return (ViewLinkImpl) findViewLink("RoleHeaderDetailLink1");
    }

    /**
     * Container's getter for ProfileHeaderLinesLink1.
     * @return ProfileHeaderLinesLink1
     */
    public ViewLinkImpl getProfileHeaderLinesLink1() {
        return (ViewLinkImpl) findViewLink("ProfileHeaderLinesLink1");
    }

    /**
     * Container's getter for UserRoleLink1.
     * @return UserRoleLink1
     */
    public ViewLinkImpl getUserRoleLink1() {
        return (ViewLinkImpl) findViewLink("UserRoleLink1");
    }

    /**
     * Container's getter for LookupContextLink1.
     * @return LookupContextLink1
     */
    public ViewLinkImpl getLookupContextLink1() {
        return (ViewLinkImpl) findViewLink("LookupContextLink1");
    }
    
    public void deleteFileLinks(String type, int employeeID){
        PreparedStatement  pst;
        try{
            pst =  getDBTransaction().createPreparedStatement("delete sys_files where file_context = ? and reference_id = ? ", 0);
            pst.setString(1, type);
            pst.setString(2, employeeID+"");
            pst.executeUpdate();
            
            getDBTransaction().commit();
            
        }catch(Exception ex){
            ex.printStackTrace();
        }
            
            
    }

    /**
     * Container's getter for ReportParameterFormVO1.
     * @return ReportParameterFormVO1
     */
    public ViewObjectImpl getReportParameterFormVO1() {
        return (ViewObjectImpl) findViewObject("ReportParameterFormVO1");
    }

    /**
     * Container's getter for UserReportsList1.
     * @return UserReportsList1
     */
    public ViewObjectImpl getUserReportsList1() {
        return (ViewObjectImpl) findViewObject("UserReportsList1");
    }

    /**
     * Container's getter for StringResources1.
     * @return StringResources1
     */
    public ViewObjectImpl getStringResources1() {
        return (ViewObjectImpl) findViewObject("StringResources1");
    }

    /**
     * Container's getter for AttachmentHeader1.
     * @return AttachmentHeader1
     */
    public ViewObjectImpl getAttachmentHeader1() {
        return (ViewObjectImpl) findViewObject("AttachmentHeader1");
    }

    /**
     * Container's getter for AttachmentLines1.
     * @return AttachmentLines1
     */
    public ViewObjectImpl getAttachmentLines1() {
        return (ViewObjectImpl) findViewObject("AttachmentLines1");
    }

    /**
     * Container's getter for AttachmentLines2.
     * @return AttachmentLines2
     */
    public ViewObjectImpl getAttachmentLines2() {
        return (ViewObjectImpl) findViewObject("AttachmentLines2");
    }

    /**
     * Container's getter for AttachmentLink1.
     * @return AttachmentLink1
     */
    public ViewLinkImpl getAttachmentLink1() {
        return (ViewLinkImpl) findViewLink("AttachmentLink1");
    }

    /**
     * Container's getter for EmployeeAttachmentsHeaderAll1.
     * @return EmployeeAttachmentsHeaderAll1
     */
    public ViewObjectImpl getEmployeeAttachmentsHeaderAll1() {
        return (ViewObjectImpl) findViewObject("EmployeeAttachmentsHeaderAll1");
    }
}

