package com.soltechsystem.model.tms.am.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Apr 30 14:30:51 PKT 2019
// ---------------------------------------------------------------------
public interface TMSAM extends ApplicationModule {
    void assignShift(String employeeID, String departmentID, String shiftID);

    void generateRoster(String employeeID, String departmentID);

    void processAttendance();

    void grantLeaves(String employeeID, String departmentID);
}

