package com.soltechsystem.model.hr.LeaveManagement.am.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 13 14:33:31 PKT 2019
// ---------------------------------------------------------------------
public interface LeaveManagementAM extends ApplicationModule {
    void logSubordinateDailyAtd(String action, int atdID);
}

