package com.soltechsystem.model.prl.Entity;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.adf.share.ADFContext;

import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Dec 25 17:28:25 PKT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PrlBanksImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        BankId,
        BankName,
        BankBranchName,
        BankBranchCode,
        BankAddress,
        CreatedBy,
        CreationDate,
        UpdatedBy,
        UpdationDate,
        VersionNumber;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int BANKID = AttributesEnum.BankId.index();
    public static final int BANKNAME = AttributesEnum.BankName.index();
    public static final int BANKBRANCHNAME = AttributesEnum.BankBranchName.index();
    public static final int BANKBRANCHCODE = AttributesEnum.BankBranchCode.index();
    public static final int BANKADDRESS = AttributesEnum.BankAddress.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int UPDATIONDATE = AttributesEnum.UpdationDate.index();
    public static final int VERSIONNUMBER = AttributesEnum.VersionNumber.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PrlBanksImpl() {
    }

    /**
     * Gets the attribute value for BankId, using the alias name BankId.
     * @return the value of BankId
     */
    public BigDecimal getBankId() {
        return (BigDecimal) getAttributeInternal(BANKID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BankId.
     * @param value value to set the BankId
     */
    public void setBankId(BigDecimal value) {
        setAttributeInternal(BANKID, value);
    }

    /**
     * Gets the attribute value for BankName, using the alias name BankName.
     * @return the value of BankName
     */
    public String getBankName() {
        return (String) getAttributeInternal(BANKNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for BankName.
     * @param value value to set the BankName
     */
    public void setBankName(String value) {
        setAttributeInternal(BANKNAME, value);
    }

    /**
     * Gets the attribute value for BankBranchName, using the alias name BankBranchName.
     * @return the value of BankBranchName
     */
    public String getBankBranchName() {
        return (String) getAttributeInternal(BANKBRANCHNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for BankBranchName.
     * @param value value to set the BankBranchName
     */
    public void setBankBranchName(String value) {
        setAttributeInternal(BANKBRANCHNAME, value);
    }

    /**
     * Gets the attribute value for BankBranchCode, using the alias name BankBranchCode.
     * @return the value of BankBranchCode
     */
    public String getBankBranchCode() {
        return (String) getAttributeInternal(BANKBRANCHCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for BankBranchCode.
     * @param value value to set the BankBranchCode
     */
    public void setBankBranchCode(String value) {
        setAttributeInternal(BANKBRANCHCODE, value);
    }

    /**
     * Gets the attribute value for BankAddress, using the alias name BankAddress.
     * @return the value of BankAddress
     */
    public String getBankAddress() {
        return (String) getAttributeInternal(BANKADDRESS);
    }

    /**
     * Sets <code>value</code> as the attribute value for BankAddress.
     * @param value value to set the BankAddress
     */
    public void setBankAddress(String value) {
        setAttributeInternal(BANKADDRESS, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public BigDecimal getCreatedBy() {
        return (BigDecimal) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(BigDecimal value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the value of CreationDate
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the value of UpdatedBy
     */
    public BigDecimal getUpdatedBy() {
        return (BigDecimal) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedBy.
     * @param value value to set the UpdatedBy
     */
    public void setUpdatedBy(BigDecimal value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for UpdationDate, using the alias name UpdationDate.
     * @return the value of UpdationDate
     */
    public Timestamp getUpdationDate() {
        return (Timestamp) getAttributeInternal(UPDATIONDATE);
    }

    /**
     * Gets the attribute value for VersionNumber, using the alias name VersionNumber.
     * @return the value of VersionNumber
     */
    public BigDecimal getVersionNumber() {
        return (BigDecimal) getAttributeInternal(VERSIONNUMBER);
    }

    /**
     * @param bankId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal bankId) {
        return new Key(new Object[] { bankId });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.soltechsystem.model.prl.Entity.PrlBanks");
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        String userid = (ADFContext.getCurrent()
                                   .getSessionScope()
                                   .get("userid") == null) ? "-1" : ADFContext.getCurrent()
                                                                              .getSessionScope()
                                                                              .get("userid")
                                                                              .toString();


        switch (operation) {

        case DML_INSERT:


            setUpdatedBy(new BigDecimal(userid));
            setCreatedBy(new BigDecimal(userid));

            break;
        case DML_UPDATE:
            setUpdatedBy(new BigDecimal(userid));

        }
        super.doDML(operation, e);
    }
}

