package com.soltechsystem.model.prl.Entity;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.adf.share.ADFContext;

import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Dec 11 20:50:37 PKT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PrlGradeLinesImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        GradeLineId,
        GradeHeaderId,
        AllowenceDeductionId,
        CreatedBy,
        CreationDate,
        UpdatedBy,
        UpdationDate,
        VersionNumber,
        Val;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int GRADELINEID = AttributesEnum.GradeLineId.index();
    public static final int GRADEHEADERID = AttributesEnum.GradeHeaderId.index();
    public static final int ALLOWENCEDEDUCTIONID = AttributesEnum.AllowenceDeductionId.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int UPDATIONDATE = AttributesEnum.UpdationDate.index();
    public static final int VERSIONNUMBER = AttributesEnum.VersionNumber.index();
    public static final int VAL = AttributesEnum.Val.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PrlGradeLinesImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.soltechsystem.model.prl.Entity.PrlGradeLines");
    }

    /**
     * Gets the attribute value for GradeLineId, using the alias name GradeLineId.
     * @return the value of GradeLineId
     */
    public BigDecimal getGradeLineId() {
        return (BigDecimal) getAttributeInternal(GRADELINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for GradeLineId.
     * @param value value to set the GradeLineId
     */
    public void setGradeLineId(BigDecimal value) {
        setAttributeInternal(GRADELINEID, value);
    }

    /**
     * Gets the attribute value for GradeHeaderId, using the alias name GradeHeaderId.
     * @return the value of GradeHeaderId
     */
    public BigDecimal getGradeHeaderId() {
        return (BigDecimal) getAttributeInternal(GRADEHEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for GradeHeaderId.
     * @param value value to set the GradeHeaderId
     */
    public void setGradeHeaderId(BigDecimal value) {
        setAttributeInternal(GRADEHEADERID, value);
    }

    /**
     * Gets the attribute value for AllowenceDeductionId, using the alias name AllowenceDeductionId.
     * @return the value of AllowenceDeductionId
     */
    public BigDecimal getAllowenceDeductionId() {
        return (BigDecimal) getAttributeInternal(ALLOWENCEDEDUCTIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for AllowenceDeductionId.
     * @param value value to set the AllowenceDeductionId
     */
    public void setAllowenceDeductionId(BigDecimal value) {
        setAttributeInternal(ALLOWENCEDEDUCTIONID, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public BigDecimal getCreatedBy() {
        return (BigDecimal) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(BigDecimal value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the value of CreationDate
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the value of UpdatedBy
     */
    public BigDecimal getUpdatedBy() {
        return (BigDecimal) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedBy.
     * @param value value to set the UpdatedBy
     */
    public void setUpdatedBy(BigDecimal value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for UpdationDate, using the alias name UpdationDate.
     * @return the value of UpdationDate
     */
    public Timestamp getUpdationDate() {
        return (Timestamp) getAttributeInternal(UPDATIONDATE);
    }

    /**
     * Gets the attribute value for VersionNumber, using the alias name VersionNumber.
     * @return the value of VersionNumber
     */
    public BigDecimal getVersionNumber() {
        return (BigDecimal) getAttributeInternal(VERSIONNUMBER);
    }

    /**
     * Gets the attribute value for Val, using the alias name Val.
     * @return the value of Val
     */
    public BigDecimal getVal() {
        return (BigDecimal) getAttributeInternal(VAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for Val.
     * @param value value to set the Val
     */
    public void setVal(BigDecimal value) {
        setAttributeInternal(VAL, value);
    }


    /**
     * @param gradeLineId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal gradeLineId) {
        return new Key(new Object[] { gradeLineId });
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        String userid = (ADFContext.getCurrent()
                                   .getSessionScope()
                                   .get("userid") == null) ? "-1" : ADFContext.getCurrent()
                                                                              .getSessionScope()
                                                                              .get("userid")
                                                                              .toString();


        switch (operation) {

        case DML_INSERT:


            setUpdatedBy(new BigDecimal(userid));
            setCreatedBy(new BigDecimal(userid));

            break;
        case DML_UPDATE:
            setUpdatedBy(new BigDecimal(userid));

        }
        super.doDML(operation, e);
    }
}

