package com.soltechsystem.model.prl.Entity;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.adf.share.ADFContext;

import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Dec 19 23:09:10 PKT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PrlLoanImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        LoanId,
        LoanDate,
        EmployeeId,
        LoanType,
        LoanAmount,
        InstallmentCount,
        InstallmentAmount,
        StopDeduction,
        CreatedBy,
        CreationDate,
        UpdatedBy,
        UpdationDate,
        VersionNumber;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return PrlLoanImpl.AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return PrlLoanImpl.AttributesEnum.firstIndex() + PrlLoanImpl.AttributesEnum
                                                                        .staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = PrlLoanImpl.AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int LOANID = AttributesEnum.LoanId.index();
    public static final int LOANDATE = AttributesEnum.LoanDate.index();
    public static final int EMPLOYEEID = AttributesEnum.EmployeeId.index();
    public static final int LOANTYPE = AttributesEnum.LoanType.index();
    public static final int LOANAMOUNT = AttributesEnum.LoanAmount.index();
    public static final int INSTALLMENTCOUNT = AttributesEnum.InstallmentCount.index();
    public static final int INSTALLMENTAMOUNT = AttributesEnum.InstallmentAmount.index();
    public static final int STOPDEDUCTION = AttributesEnum.StopDeduction.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int UPDATIONDATE = AttributesEnum.UpdationDate.index();
    public static final int VERSIONNUMBER = AttributesEnum.VersionNumber.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PrlLoanImpl() {
    }

    /**
     * Gets the attribute value for LoanId, using the alias name LoanId.
     * @return the value of LoanId
     */
    public BigDecimal getLoanId() {
        return (BigDecimal) getAttributeInternal(LOANID);
    }

    /**
     * Sets <code>value</code> as the attribute value for LoanId.
     * @param value value to set the LoanId
     */
    public void setLoanId(BigDecimal value) {
        setAttributeInternal(LOANID, value);
    }

    /**
     * Gets the attribute value for LoanDate, using the alias name LoanDate.
     * @return the value of LoanDate
     */
    public Timestamp getLoanDate() {
        return (Timestamp) getAttributeInternal(LOANDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LoanDate.
     * @param value value to set the LoanDate
     */
    public void setLoanDate(Timestamp value) {
        setAttributeInternal(LOANDATE, value);
    }

    /**
     * Gets the attribute value for EmployeeId, using the alias name EmployeeId.
     * @return the value of EmployeeId
     */
    public BigDecimal getEmployeeId() {
        return (BigDecimal) getAttributeInternal(EMPLOYEEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for EmployeeId.
     * @param value value to set the EmployeeId
     */
    public void setEmployeeId(BigDecimal value) {
        setAttributeInternal(EMPLOYEEID, value);
    }

    /**
     * Gets the attribute value for LoanType, using the alias name LoanType.
     * @return the value of LoanType
     */
    public BigDecimal getLoanType() {
        return (BigDecimal) getAttributeInternal(LOANTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LoanType.
     * @param value value to set the LoanType
     */
    public void setLoanType(BigDecimal value) {
        setAttributeInternal(LOANTYPE, value);
    }

    /**
     * Gets the attribute value for LoanAmount, using the alias name LoanAmount.
     * @return the value of LoanAmount
     */
    public BigDecimal getLoanAmount() {
        return (BigDecimal) getAttributeInternal(LOANAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for LoanAmount.
     * @param value value to set the LoanAmount
     */
    public void setLoanAmount(BigDecimal value) {
        setAttributeInternal(LOANAMOUNT, value);
    }

    /**
     * Gets the attribute value for InstallmentCount, using the alias name InstallmentCount.
     * @return the value of InstallmentCount
     */
    public BigDecimal getInstallmentCount() {
        return (BigDecimal) getAttributeInternal(INSTALLMENTCOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for InstallmentCount.
     * @param value value to set the InstallmentCount
     */
    public void setInstallmentCount(BigDecimal value) {
        setAttributeInternal(INSTALLMENTCOUNT, value);
    }

    /**
     * Gets the attribute value for InstallmentAmount, using the alias name InstallmentAmount.
     * @return the value of InstallmentAmount
     */
    public BigDecimal getInstallmentAmount() {
        return (BigDecimal) getAttributeInternal(INSTALLMENTAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for InstallmentAmount.
     * @param value value to set the InstallmentAmount
     */
    public void setInstallmentAmount(BigDecimal value) {
        setAttributeInternal(INSTALLMENTAMOUNT, value);
    }

    /**
     * Gets the attribute value for StopDeduction, using the alias name StopDeduction.
     * @return the value of StopDeduction
     */
    public String getStopDeduction() {
        return (String) getAttributeInternal(STOPDEDUCTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for StopDeduction.
     * @param value value to set the StopDeduction
     */
    public void setStopDeduction(String value) {
        setAttributeInternal(STOPDEDUCTION, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public BigDecimal getCreatedBy() {
        return (BigDecimal) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(BigDecimal value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the value of CreationDate
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the value of UpdatedBy
     */
    public BigDecimal getUpdatedBy() {
        return (BigDecimal) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedBy.
     * @param value value to set the UpdatedBy
     */
    public void setUpdatedBy(BigDecimal value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for UpdationDate, using the alias name UpdationDate.
     * @return the value of UpdationDate
     */
    public Timestamp getUpdationDate() {
        return (Timestamp) getAttributeInternal(UPDATIONDATE);
    }

    /**
     * Gets the attribute value for VersionNumber, using the alias name VersionNumber.
     * @return the value of VersionNumber
     */
    public BigDecimal getVersionNumber() {
        return (BigDecimal) getAttributeInternal(VERSIONNUMBER);
    }

    /**
     * @param loanId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal loanId) {
        return new Key(new Object[] { loanId });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.soltechsystem.model.hr.Entity.PrlLoan");
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        String userid = (ADFContext.getCurrent()
                                   .getSessionScope()
                                   .get("userid") == null) ? "-1" : ADFContext.getCurrent()
                                                                              .getSessionScope()
                                                                              .get("userid")
                                                                              .toString();


        switch (operation) {

        case DML_INSERT:


            setUpdatedBy(new BigDecimal(userid));
            setCreatedBy(new BigDecimal(userid));
            
            break;
        case DML_UPDATE:
            setUpdatedBy(new BigDecimal(userid));

        }
        super.doDML(operation, e);
    }
}

