package com.soltechsystem.model.prl.Entity;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.adf.share.ADFContext;

import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Dec 22 22:33:36 PKT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PrlSalaryPeriodHeaderImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        PeriodId,
        PeriodYear,
        PeriodYearStart,
        PeriodYearEnd,
        CreatedBy,
        CreationDate,
        UpdatedBy,
        UpdationDate,
        VersionNumber;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int PERIODID = AttributesEnum.PeriodId.index();
    public static final int PERIODYEAR = AttributesEnum.PeriodYear.index();
    public static final int PERIODYEARSTART = AttributesEnum.PeriodYearStart.index();
    public static final int PERIODYEAREND = AttributesEnum.PeriodYearEnd.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int UPDATIONDATE = AttributesEnum.UpdationDate.index();
    public static final int VERSIONNUMBER = AttributesEnum.VersionNumber.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PrlSalaryPeriodHeaderImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.soltechsystem.model.prl.Entity.PrlSalaryPeriodHeader");
    }


    /**
     * Gets the attribute value for PeriodId, using the alias name PeriodId.
     * @return the value of PeriodId
     */
    public BigDecimal getPeriodId() {
        return (BigDecimal) getAttributeInternal(PERIODID);
    }

    /**
     * Sets <code>value</code> as the attribute value for PeriodId.
     * @param value value to set the PeriodId
     */
    public void setPeriodId(BigDecimal value) {
        setAttributeInternal(PERIODID, value);
    }

    /**
     * Gets the attribute value for PeriodYear, using the alias name PeriodYear.
     * @return the value of PeriodYear
     */
    public String getPeriodYear() {
        return (String) getAttributeInternal(PERIODYEAR);
    }

    /**
     * Sets <code>value</code> as the attribute value for PeriodYear.
     * @param value value to set the PeriodYear
     */
    public void setPeriodYear(String value) {
        setAttributeInternal(PERIODYEAR, value);
    }

    /**
     * Gets the attribute value for PeriodYearStart, using the alias name PeriodYearStart.
     * @return the value of PeriodYearStart
     */
    public Timestamp getPeriodYearStart() {
        return (Timestamp) getAttributeInternal(PERIODYEARSTART);
    }

    /**
     * Sets <code>value</code> as the attribute value for PeriodYearStart.
     * @param value value to set the PeriodYearStart
     */
    public void setPeriodYearStart(Timestamp value) {
        setAttributeInternal(PERIODYEARSTART, value);
    }

    /**
     * Gets the attribute value for PeriodYearEnd, using the alias name PeriodYearEnd.
     * @return the value of PeriodYearEnd
     */
    public Timestamp getPeriodYearEnd() {
        return (Timestamp) getAttributeInternal(PERIODYEAREND);
    }

    /**
     * Sets <code>value</code> as the attribute value for PeriodYearEnd.
     * @param value value to set the PeriodYearEnd
     */
    public void setPeriodYearEnd(Timestamp value) {
        setAttributeInternal(PERIODYEAREND, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public BigDecimal getCreatedBy() {
        return (BigDecimal) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(BigDecimal value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the value of CreationDate
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the value of UpdatedBy
     */
    public BigDecimal getUpdatedBy() {
        return (BigDecimal) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedBy.
     * @param value value to set the UpdatedBy
     */
    public void setUpdatedBy(BigDecimal value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for UpdationDate, using the alias name UpdationDate.
     * @return the value of UpdationDate
     */
    public Timestamp getUpdationDate() {
        return (Timestamp) getAttributeInternal(UPDATIONDATE);
    }

    /**
     * Gets the attribute value for VersionNumber, using the alias name VersionNumber.
     * @return the value of VersionNumber
     */
    public BigDecimal getVersionNumber() {
        return (BigDecimal) getAttributeInternal(VERSIONNUMBER);
    }


    /**
     * @param periodId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal periodId) {
        return new Key(new Object[] { periodId });
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        String userid = (ADFContext.getCurrent()
                                   .getSessionScope()
                                   .get("userid") == null) ? "-1" : ADFContext.getCurrent()
                                                                              .getSessionScope()
                                                                              .get("userid")
                                                                              .toString();


        switch (operation) {

        case DML_INSERT:


            setUpdatedBy(new BigDecimal(userid));
            setCreatedBy(new BigDecimal(userid));
            
            break;
        case DML_UPDATE:
            setUpdatedBy(new BigDecimal(userid));

        }
        super.doDML(operation, e);
    }
}

