package com.soltechsystem.model.recruitment.am.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 18 20:19:42 PKT 2019
// ---------------------------------------------------------------------
public interface RecruitmentAM extends ApplicationModule {
    void deleteFileLinks(String type, int referenceID);

    String interviewDone(int applicationID);
}

