package com.soltechsystem.model.hr.LeaveManagement.am;

import com.soltechsystem.model.hr.LeaveManagement.am.common.LeaveManagementAM;

import java.sql.CallableStatement;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 13 14:31:53 PKT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LeaveManagementAMImpl extends ApplicationModuleImpl implements LeaveManagementAM {
    /**
     * This is the default constructor (do not remove).
     */
    public LeaveManagementAMImpl() {
    }

    /**
     * Container's getter for EmployeeLeavesView1.
     * @return EmployeeLeavesView1
     */
    public ViewObjectImpl getEmployeeLeavesView1() {
        return (ViewObjectImpl) findViewObject("EmployeeLeavesView1");
    }

    /**
     * Container's getter for LeaveTypesList1.
     * @return LeaveTypesList1
     */
    public ViewObjectImpl getLeaveTypesList1() {
        return (ViewObjectImpl) findViewObject("LeaveTypesList1");
    }

    /**
     * Container's getter for LeaveStatusList1.
     * @return LeaveStatusList1
     */
    public ViewObjectImpl getLeaveStatusList1() {
        return (ViewObjectImpl) findViewObject("LeaveStatusList1");
    }

    /**
     * Container's getter for LeaveBalance1.
     * @return LeaveBalance1
     */
    public ViewObjectImpl getLeaveBalance1() {
        return (ViewObjectImpl) findViewObject("LeaveBalance1");
    }

    /**
     * Container's getter for AttendanceReport1.
     * @return AttendanceReport1
     */
    public ViewObjectImpl getAttendanceReport1() {
        return (ViewObjectImpl) findViewObject("AttendanceReport1");
    }

    /**
     * Container's getter for LeaveReport1.
     * @return LeaveReport1
     */
    public ViewObjectImpl getLeaveReport1() {
        return (ViewObjectImpl) findViewObject("LeaveReport1");
    }

    /**
     * Container's getter for SubordinateDailyAttendance1.
     * @return SubordinateDailyAttendance1
     */
    public ViewObjectImpl getSubordinateDailyAttendance1() {
        return (ViewObjectImpl) findViewObject("SubordinateDailyAttendance1");
    }

    public void logSubordinateDailyAtd(String action, int atdID) {
        CallableStatement cst = null;
        try {
            cst = getDBTransaction().createCallableStatement("{call sthrms.log_subordinate_dailiy_atd(?,?)}", 0);
            cst.setString(1, action);
            cst.setInt(2, atdID);


            cst.executeUpdate();


        } catch (Exception ex) {
            ex.printStackTrace();

        }
    }
}

