package com.soltechsystem.model.sys.Entity;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.adf.share.ADFContext;

import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Nov 30 20:36:01 PKT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HrLookupValuesImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        LookupId,
        LookupValue,
        CreatedBy,
        CreationDate,
        UpdatedBy,
        UpdationDate,
        VersionNumber,
        LookupContext,
        ValueDescription,
        Enabled;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int LOOKUPID = AttributesEnum.LookupId.index();
    public static final int LOOKUPVALUE = AttributesEnum.LookupValue.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int UPDATIONDATE = AttributesEnum.UpdationDate.index();
    public static final int VERSIONNUMBER = AttributesEnum.VersionNumber.index();
    public static final int LOOKUPCONTEXT = AttributesEnum.LookupContext.index();
    public static final int VALUEDESCRIPTION = AttributesEnum.ValueDescription.index();
    public static final int ENABLED = AttributesEnum.Enabled.index();

    /**
     * This is the default constructor (do not remove).
     */
    public HrLookupValuesImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.soltechsystem.model.sys.Entity.HrLookupValues");
    }


    /**
     * Gets the attribute value for LookupId, using the alias name LookupId.
     * @return the value of LookupId
     */
    public BigDecimal getLookupId() {
        return (BigDecimal) getAttributeInternal(LOOKUPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for LookupId.
     * @param value value to set the LookupId
     */
    public void setLookupId(BigDecimal value) {
        setAttributeInternal(LOOKUPID, value);
    }

    /**
     * Gets the attribute value for LookupValue, using the alias name LookupValue.
     * @return the value of LookupValue
     */
    public String getLookupValue() {
        return (String) getAttributeInternal(LOOKUPVALUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LookupValue.
     * @param value value to set the LookupValue
     */
    public void setLookupValue(String value) {
        setAttributeInternal(LOOKUPVALUE, value);
    }


    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public BigDecimal getCreatedBy() {
        return (BigDecimal) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(BigDecimal value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the value of CreationDate
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the value of UpdatedBy
     */
    public BigDecimal getUpdatedBy() {
        return (BigDecimal) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedBy.
     * @param value value to set the UpdatedBy
     */
    public void setUpdatedBy(BigDecimal value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for UpdationDate, using the alias name UpdationDate.
     * @return the value of UpdationDate
     */
    public Timestamp getUpdationDate() {
        return (Timestamp) getAttributeInternal(UPDATIONDATE);
    }

    /**
     * Gets the attribute value for VersionNumber, using the alias name VersionNumber.
     * @return the value of VersionNumber
     */
    public BigDecimal getVersionNumber() {
        return (BigDecimal) getAttributeInternal(VERSIONNUMBER);
    }


    /**
     * Gets the attribute value for LookupContext, using the alias name LookupContext.
     * @return the value of LookupContext
     */
    public BigDecimal getLookupContext() {
        return (BigDecimal) getAttributeInternal(LOOKUPCONTEXT);
    }

    /**
     * Sets <code>value</code> as the attribute value for LookupContext.
     * @param value value to set the LookupContext
     */
    public void setLookupContext(BigDecimal value) {
        setAttributeInternal(LOOKUPCONTEXT, value);
    }


    /**
     * Gets the attribute value for ValueDescription, using the alias name ValueDescription.
     * @return the value of ValueDescription
     */
    public String getValueDescription() {
        return (String) getAttributeInternal(VALUEDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for ValueDescription.
     * @param value value to set the ValueDescription
     */
    public void setValueDescription(String value) {
        setAttributeInternal(VALUEDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for Enabled, using the alias name Enabled.
     * @return the value of Enabled
     */
    public String getEnabled() {
        return (String) getAttributeInternal(ENABLED);
    }

    /**
     * Sets <code>value</code> as the attribute value for Enabled.
     * @param value value to set the Enabled
     */
    public void setEnabled(String value) {
        setAttributeInternal(ENABLED, value);
    }

    /**
     * @param lookupId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal lookupId) {
        return new Key(new Object[] { lookupId });
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        String userid = (ADFContext.getCurrent()
                                   .getSessionScope()
                                   .get("userid") == null) ? "-1" : ADFContext.getCurrent()
                                                                              .getSessionScope()
                                                                              .get("userid")
                                                                              .toString();


        switch (operation) {

        case DML_INSERT:


            setUpdatedBy(new BigDecimal(userid));
            setCreatedBy(new BigDecimal(userid));

            break;
        case DML_UPDATE:
            setUpdatedBy(new BigDecimal(userid));

        }
        super.doDML(operation, e);
    }
}

